format_version: 3
pipelines:
  test:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://bitbucket.org/vijay256/demo.git
        username: vijay256
        shallow_clone: false
        auto_update: true
        branch: master
        password: Vijay@321
    stages:
    - Clean:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          defaultJob:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - clean
                command: mvn
                run_if: passed
    - Compile:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          Compilation:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - compile
                command: mvn
                run_if: passed
    - Package:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          Package:
            timeout: 0
            artifacts:
            - build:
                source: '**/*.war'
                destination: pkg
            - build:
                source: '**/*.jar'
                destination: pkg
            tasks:
            - exec:
                arguments:
                - package
                command: mvn
                run_if: passed