pipeline {
  options {
	buildDiscarder(logRotator(numToKeepStr: '02'))
  }
    agent any
        parameters {
            string(
                name:'URL',
                defaultValue:"default",
                description: "enter URL")
            string(
                name:'groupid',
                defaultValue:'default',
                description:'enter groupid')
            string(
                name:'artifactid1',
                defaultValue:'default',
                description:'enter artifactid1')
            string(
                name:'image',
                defaultValue:'default',
                description:'enter image name')
        }
        stages {
            stage('SCM') {
                steps {
                    checkout scm
                    }
                }
                stage('Build') {
                    steps {
                        script {
                            sh '''
                                mvn clean
                                mvn clean install
                            '''
                        }
                    }
                }
                stage('Sonar-Analysis') {
                    steps {
                        script {
                            sh '''
                                ls -lrt
                            '''
                        }
                    }
                }
                stage('Test-Cases') {
                    steps {
                        script {
                            sh '''
                                ls
                            '''
                        }
                    }
                }
                stage('Package') {
                    steps {
                        script {
                            sh '''
                                mvn package 
                            '''
                        }
                    }
                }
                stage('Archive artifact') {
                  steps {
                    echo 'I am successfull completed :)'
                    archiveArtifacts '**/*.jar'
                  }
                }
                stage('Deploy-To-Nexus') {
                  steps {
                    script {
                    	sh '''
                        	mvn deploy:deploy-file -DgroupId=chatak-afcs -DartifactId=afcs-server-0.0.1 -Dversion=4.0.0-SNAPSHOT -DgeneratePom=true -Dpackaging=jar -DrepositoryId=nexus -Durl=http://192.168.0.91:8081/repository/maven-snapshots/ -Dfile=transit-services/target/afcs-server-0.0.1.jar
						'''
                    }
                  }
                }
                stage('Artifact-Download') {
                    steps {
                        script {
                            sh '''
                                cd devops/QA/afcs
                                sh file.sh
                            '''
                        }
                    }
                }
                stage('Build-APP-Image') {
                    steps {
                        script {
                            sh '''
                                cd devops/QA/afcs
                                docker build -t $image:${BUILD_NUMBER} .
                            '''
                        }
                    }
                }
                stage('Push-Docker-IMAGE') {
                    steps {
                        script {
                            sh '''
                                cd devops/QA/afcs
                                sh docker.sh
                            '''
                        }
                    }
                }
                stage('RUN-Image') {
                    steps {
                        script {
                            sh '''
                                cd devops/QA/afcs
                                ansible-playbook playbook.yml -i hosts --extra-vars "registry=192.168.0.91:8082 build_number=${BUILD_NUMBER}"
                            '''
                        }
                    }
                }
        }
}
