--------------------------------------------------------
--  DDL for Table COUNTRY
--------------------------------------------------------
CREATE TABLE COUNTRY (
    ID                 	NUMBER(20) 	NOT NULL,
	NAME		        VARCHAR2(255)
);

ALTER TABLE COUNTRY ADD CONSTRAINT COUNTRY_PK PRIMARY KEY(ID);

--------------------------------------------------------
--  DDL for Table STATE
--------------------------------------------------------
CREATE TABLE STATE (
    ID                 	NUMBER(20) 	NOT NULL,
	COUNTRY_ID			NUMBER(20),
	NAME			    VARCHAR2(255)
);

ALTER TABLE STATE ADD CONSTRAINT STATE_PK PRIMARY KEY(ID);
ALTER TABLE STATE ADD FOREIGN KEY(COUNTRY_ID) REFERENCES COUNTRY(ID);

--------------------------------------------------------
--  DDL for Table USER_ROLE
--------------------------------------------------------
CREATE TABLE USER_ROLE (
	USER_ROLE_ID 			NUMBER(20)    	NOT NULL,
    NAME                    VARCHAR2(100)    NOT NULL,
    DESCRIPTION             VARCHAR2(255)   DEFAULT NULL,
    STATUS                  VARCHAR2(50)    NOT NULL,
    ROLE_TYPE               VARCHAR2(50)   	DEFAULT NULL,
    REASON 					VARCHAR2(500)  	DEFAULT NULL,
    CREATED_DATE            TIMESTAMP	  	NOT NULL,
    UPDATED_DATE            TIMESTAMP,
    CREATED_BY    			VARCHAR2(50)    NOT NULL,
    UPDATED_BY              VARCHAR2(50)
);

ALTER TABLE USER_ROLE ADD CONSTRAINT USER_ROLE_PK PRIMARY KEY(USER_ROLE_ID);
CREATE SEQUENCE SEQ_USER_ROLE MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;	
  
--------------------------------------------------------
--  DDL for Table ADMIN_USER
--------------------------------------------------------
CREATE TABLE ADMIN_USER (
    ADMIN_USER_ID     		NUMBER(20)        	NOT NULL,
    USER_ROLE_ID      		NUMBER(20)         	NOT NULL,
    ENTITY_ID      		    NUMBER(20)         	DEFAULT NULL,
    USERNAME				VARCHAR2(50)       	NOT NULL,
    EMAIL             		VARCHAR2(100)      	NOT NULL,
    EMAIL_TOKEN 			VARCHAR2(255)      	DEFAULT NULL,
    PASSWORD          		VARCHAR2(100)      	NOT NULL,
    USER_TYPE         		VARCHAR2(50)       	DEFAULT NULL,
    FIRST_NAME        		VARCHAR2(50)       	NOT NULL,
    LAST_NAME         		VARCHAR2(50)       	DEFAULT NULL,
    PHONE             		VARCHAR2(20)       	NOT NULL,
    PREVIOUS_PASSWORDS  	VARCHAR2(2500)     	DEFAULT NULL,
    LAST_PASSWORD_CHANGE 	TIMESTAMP          	DEFAULT NULL,
    PASS_RETRY_COUNT     	NUMBER(2)          	DEFAULT 0,
    STATUS            		VARCHAR2(50)       	NOT NULL,
    LOGIN_MODE 		  		NUMBER(10),
    SECURITY_QUESTION 		VARCHAR2(100),
    SECURITY_ANSWER   		VARCHAR2(100),
    REASON 					VARCHAR2(500) 		DEFAULT NULL,
    CREATED_DATE      		TIMESTAMP         	NOT NULL,
    UPDATED_DATE      		TIMESTAMP,
    CREATED_BY              VARCHAR2(50)       	NOT NULL,
    UPDATED_BY        		VARCHAR2(50),
    EXTENSION               VARCHAR2(5)
);
  
ALTER TABLE ADMIN_USER ADD CONSTRAINT ADMIN_USER_PK PRIMARY KEY(ADMIN_USER_ID);
ALTER TABLE ADMIN_USER ADD FOREIGN KEY(USER_ROLE_ID) REFERENCES USER_ROLE(USER_ROLE_ID);
CREATE SEQUENCE SEQ_ADMIN_USER MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table ADMIN_USER_H
--------------------------------------------------------
CREATE TABLE ADMIN_USER_H (
    ID   					NUMBER(20)        	NOT NULL,
    ADMIN_USER_ID     		NUMBER(20)        	NOT NULL,
    USER_ROLE_ID      		NUMBER(20)         	NOT NULL,
    ENTITY_ID      		    NUMBER(20)         	DEFAULT NULL,
    USERNAME				VARCHAR2(50)       	NOT NULL,
    EMAIL             		VARCHAR2(100)      	NOT NULL,
    EMAIL_TOKEN 			VARCHAR2(255)      	DEFAULT NULL,
    PASSWORD          		VARCHAR2(100)      	NOT NULL,
    USER_TYPE         		VARCHAR2(50)       	DEFAULT NULL,
    FIRST_NAME        		VARCHAR2(50)       	NOT NULL,
    LAST_NAME         		VARCHAR2(50)       	DEFAULT NULL,
    PHONE             		VARCHAR2(20)       	NOT NULL,
    PREVIOUS_PASSWORDS  	VARCHAR2(2500)     	DEFAULT NULL,
    LAST_PASSWORD_CHANGE 	TIMESTAMP          	DEFAULT NULL,
    PASS_RETRY_COUNT     	NUMBER(2)          	DEFAULT 0,
    STATUS            		VARCHAR2(50)       	NOT NULL,
    LOGIN_MODE 		  		NUMBER(10),
    SECURITY_QUESTION 		VARCHAR2(100),
    SECURITY_ANSWER   		VARCHAR2(100),
    REASON 					VARCHAR2(500) 		DEFAULT NULL,
    CREATED_DATE      		TIMESTAMP         	NOT NULL,
    UPDATED_DATE      		TIMESTAMP,
    CREATED_BY              VARCHAR2(50)       	NOT NULL,
    UPDATED_BY        		VARCHAR2(50),
    EXTENSION               VARCHAR2(5)
);
  
ALTER TABLE ADMIN_USER_H ADD CONSTRAINT ADMIN_USER_H_PK PRIMARY KEY(ID);
ALTER TABLE ADMIN_USER_H ADD FOREIGN KEY(ADMIN_USER_ID) REFERENCES ADMIN_USER(ADMIN_USER_ID);
CREATE SEQUENCE SEQ_ADMIN_USER_HISTORY MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table PORTAL_FEATURE
--------------------------------------------------------
CREATE TABLE PREPAID_FEATURE (
	FEATURE_ID                   NUMBER(20)  	NOT NULL,               
    NAME                         VARCHAR2(50)   NOT NULL,            
    FEATURE_LEVEL                NUMBER(2)      NOT NULL,
    ROLE_TYPE                    VARCHAR2(50)   DEFAULT NULL,  
    REF_FEATURE_ID               NUMBER(20)     DEFAULT NULL,
    STATUS                       VARCHAR2(50)   NOT NULL,
    CREATED_DATE                 TIMESTAMP      NOT NULL
);

ALTER TABLE PREPAID_FEATURE ADD CONSTRAINT PREPAID_FEATURE_PK PRIMARY KEY(FEATURE_ID);

--------------------------------------------------------
--  DDL for Table PORTAL_ROLE_FEATURE_MAP
--------------------------------------------------------
CREATE TABLE PORTAL_ROLE_FEATURE_MAP (
	ROLE_FEATURE_MAP_ID          NUMBER(20),
	USER_ROLE_ID                 NUMBER(20), 
    FEATURE_ID                   NUMBER(20),
    CREATED_DATE                 TIMESTAMP		NOT NULL,
    UPDATED_DATE                 TIMESTAMP,
    CREATED_BY    				  VARCHAR2(50) 	NOT NULL,
    UPDATED_BY                   VARCHAR2(50)
);

ALTER TABLE PORTAL_ROLE_FEATURE_MAP ADD CONSTRAINT PORTAL_ROLE_FMAP_PK PRIMARY KEY(ROLE_FEATURE_MAP_ID);
ALTER TABLE PORTAL_ROLE_FEATURE_MAP ADD FOREIGN KEY(USER_ROLE_ID) REFERENCES USER_ROLE(USER_ROLE_ID);
ALTER TABLE PORTAL_ROLE_FEATURE_MAP ADD FOREIGN KEY(FEATURE_ID) REFERENCES PREPAID_FEATURE(FEATURE_ID);
CREATE SEQUENCE SEQ_PORTAL_ROLE_FEATURE_MAP MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table BANK
--------------------------------------------------------
CREATE TABLE BANK (
    BANK_ID              	NUMBER(20)     	NOT NULL,
    BANK_NAME            	VARCHAR2(100),
    BANK_CODE            	VARCHAR2(50),
    SETTL_ROUTING_NUMBER 	VARCHAR2(50),
    SETTL_ACCOUNT_NUMBER 	VARCHAR2(50),
    ADDRESS1             	VARCHAR2(100),
    ADDRESS2             	VARCHAR2(100),
    CITY                 	VARCHAR2(50),
    STATE                	VARCHAR2(50),
    ZIP                  	VARCHAR2(20),
    COUNTRY              	VARCHAR2(50),
    CONTACT_PERSON_NAME  	VARCHAR2(50),
    CONTACT_PERSON_PHONE 	VARCHAR2(50),
    CONTACT_PERSON_FAX   	VARCHAR2(50),
    CONTACT_PERSON_EMAIL 	VARCHAR2(50),
    CONTACT_PERSON_CELL  	VARCHAR2(50),
    STATUS               	VARCHAR2(50),
    REASON 				 	VARCHAR2(500),
    CREATED_DATE         	TIMESTAMP			NOT NULL,
    UPDATED_DATE         	TIMESTAMP,
    CREATED_BY    		 	VARCHAR2(50)   		NOT NULL,
    UPDATED_BY           	VARCHAR2(50),
    EXTENSION               VARCHAR2(5)
);

ALTER TABLE BANK ADD CONSTRAINT BANK_PK PRIMARY KEY(BANK_ID);
CREATE SEQUENCE SEQ_BANK MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table BIN
--------------------------------------------------------
CREATE TABLE BIN (
    BIN                			NUMBER(20) 		NOT NULL,
    BANK_ID            			NUMBER(20) 		NOT NULL,
    BIN_EFFECTIVE_DATE 			TIMESTAMP,
    PAYMENT_SCHEME_NAME 		VARCHAR2(50) 	NOT NULL,
    STATUS             			VARCHAR2(50),
    REASON 			   			VARCHAR2(500),
    CREATED_DATE       			TIMESTAMP		NOT NULL,
    UPDATED_DATE       			TIMESTAMP,
    CREATED_BY    	   			VARCHAR2(50) 	NOT NULL,
    UPDATED_BY         			VARCHAR2(50)
);

ALTER TABLE BIN ADD CONSTRAINT BIN_PK PRIMARY KEY(BIN);
ALTER TABLE BIN ADD FOREIGN KEY(BANK_ID) REFERENCES BANK(BANK_ID);

--------------------------------------------------------
--  DDL for Table PROGRAM_MANAGER
--------------------------------------------------------
CREATE TABLE PROGRAM_MANAGER (
    ID    					NUMBER(20) 		NOT NULL,
    COMPANY_NAME  			VARCHAR2(100),
    BUSINESS_NAME 			VARCHAR2(100),
    PROGRAM_MANAGER_NAME  	VARCHAR2(255),
    CONTACT_NAME  			VARCHAR2(50),
    CONTACT_PHONE 			VARCHAR2(20),
    CONTACT_EMAIL 			VARCHAR2(100),
    STATUS        			VARCHAR2(50),
    REASON 		  			VARCHAR2(500),
    PROGRAMLOGO				BLOB,
    CREATED_DATE  			TIMESTAMP 		NOT NULL,
    UPDATED_DATE  			TIMESTAMP,
    CREATED_BY    			VARCHAR2(50) 	NOT NULL,
    UPDATED_BY    			VARCHAR2(50),
    EXTENSION               VARCHAR2(5)
);
  
ALTER TABLE PROGRAM_MANAGER ADD CONSTRAINT PROGRAM_MANAGER_PK PRIMARY KEY(ID);
CREATE SEQUENCE SEQ_PROGRAM_MANAGER MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table BANK_PROGRAM_MANAGER_MAP
--------------------------------------------------------
CREATE TABLE BANK_PROGRAM_MANAGER_MAP (
    ID    					NUMBER(20) 		NOT NULL,
    BANK_ID  				NUMBER(20),
    PROGRAM_MANAGER_ID 		NUMBER(20)
);
  
ALTER TABLE BANK_PROGRAM_MANAGER_MAP ADD CONSTRAINT BANK_PROGRAM_MANAGER_MAP_PK PRIMARY KEY(ID);
ALTER TABLE BANK_PROGRAM_MANAGER_MAP ADD FOREIGN KEY(BANK_ID) REFERENCES BANK(BANK_ID);
ALTER TABLE BANK_PROGRAM_MANAGER_MAP ADD FOREIGN KEY(PROGRAM_MANAGER_ID) REFERENCES PROGRAM_MANAGER(ID);
CREATE SEQUENCE SEQ_BANK_PROGRAM_MANAGER_MAP MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table PROGRAM_MANAGER_ACCOUNT
--------------------------------------------------------
CREATE TABLE PROGRAM_MANAGER_ACCOUNT (
    ID  					NUMBER(20) 		NOT NULL,  
    PROGRAM_MANAGER_ID    	NUMBER(20),
    ACCOUNT_NUMBER  		NUMBER(15) 	NOT NULL,
	ACCOUNT_TYPE      		VARCHAR2(50),
    AVAILABLE_BALANCE		NUMBER(20) 	DEFAULT 0,
	CURRENT_BALANCE			NUMBER(20) 	DEFAULT 0,
	STATUS      			VARCHAR2(50),
	LAST_TXN_NUMBER			VARCHAR2(50),
    CREATED_DATE        	TIMESTAMP		NOT NULL,
    UPDATED_DATE        	TIMESTAMP,
    CREATED_BY    			VARCHAR2(50) 	NOT NULL,
    UPDATED_BY          	VARCHAR2(50)
);
  
ALTER TABLE PROGRAM_MANAGER_ACCOUNT ADD CONSTRAINT PROGRAM_MANAGER_ACCOUNT_PK PRIMARY KEY(ID);
ALTER TABLE PROGRAM_MANAGER_ACCOUNT ADD CONSTRAINT PM_ACCOUNT_NUMBER_UNIQUE UNIQUE(ACCOUNT_NUMBER);
CREATE SEQUENCE SEQ_PROGRAM_MANAGER_ACCOUNT MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;
CREATE SEQUENCE SEQ_PM_ACCOUNT_NUMBER MINVALUE 10000 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 10000 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table PROGRAM_MANAGER_ACCOUNT_H
--------------------------------------------------------
CREATE TABLE PROGRAM_MANAGER_ACCOUNT_H (
  	PROGRAM_MANAGER_HISTORY_ID		NUMBER(20) 		NOT NULL,
    PROGRAM_MANAGER_ACCOUNT_ID  	NUMBER(20) 		NOT NULL,  
    PROGRAM_MANAGER_ID    			NUMBER(20),
    ACCOUNT_NUMBER  				NUMBER(15) 	NOT NULL,
	ACCOUNT_TYPE      				VARCHAR2(50),
    AVAILABLE_BALANCE				NUMBER(20) 	DEFAULT 0,
	CURRENT_BALANCE					NUMBER(20) 	DEFAULT 0,
	STATUS      					VARCHAR2(50),
    CREATED_DATE        			TIMESTAMP		NOT NULL,
    UPDATED_DATE        			TIMESTAMP,
    CREATED_BY    					VARCHAR2(20) 	NOT NULL,
    UPDATED_BY          			VARCHAR2(20),
    TXN_NUMBER 		    			VARCHAR2(50)
);
  
ALTER TABLE PROGRAM_MANAGER_ACCOUNT_H ADD CONSTRAINT PROGRAM_MANAGER_HISTORY_ID_PK PRIMARY KEY(PROGRAM_MANAGER_HISTORY_ID);
CREATE SEQUENCE SEQ_PROGRAM_MANAGER_ACCOUNT_H MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table PARTNER
--------------------------------------------------------
CREATE TABLE PARTNER (
    PARTNER_ID    			NUMBER(20)       	NOT NULL,
    PROGRAM_MANAGER_ID    	NUMBER(20),
    COMPANY_NAME  			VARCHAR2(100),
    BUSINESS_NAME 			VARCHAR2(100),
    PARTNER_NAME  			VARCHAR2(255)     	DEFAULT NULL,
    ADDRESS1      			VARCHAR2(100),
    ADDRESS2      			VARCHAR2(100),
    CITY          			VARCHAR2(50),
    STATE         			VARCHAR2(50),
    ZIP           			VARCHAR2(20),
    COUNTRY       			VARCHAR2(50),
    LOGO 					BLOB,
    CONTACT_NAME  			VARCHAR2(50),
    CONTACT_PHONE 			VARCHAR2(20),
    STATUS        			VARCHAR2(50),
	PARTNER_CLIENT_ID 		VARCHAR2(50),
	WHITELIST_IP_ADDRESS 	VARCHAR2(1000),
    REASON 		  			VARCHAR2(500),
    CREATED_DATE  			TIMESTAMP			NOT NULL,
    UPDATED_DATE  			TIMESTAMP,
    CREATED_BY    			VARCHAR2(50)       	NOT NULL,
    UPDATED_BY    			VARCHAR2(50),
    EXTENSION               VARCHAR2(5)
);
  
ALTER TABLE PARTNER ADD CONSTRAINT PARTNER_PK PRIMARY KEY(PARTNER_ID);
ALTER TABLE PARTNER ADD FOREIGN KEY(PROGRAM_MANAGER_ID) REFERENCES PROGRAM_MANAGER(ID);
ALTER TABLE PARTNER ADD CONSTRAINT PARTNER_CLIENT_ID_UNIQUE UNIQUE(PARTNER_CLIENT_ID);
CREATE SEQUENCE SEQ_PARTNER MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table PARTNER_ACCOUNT
--------------------------------------------------------
CREATE TABLE PARTNER_ACCOUNT (
    PARTNER_ACCOUNT_ID  NUMBER(20) 		NOT NULL,  
    PARTNER_ID    		NUMBER(20),
    ACCOUNT_NUMBER  	NUMBER(15) 	NOT NULL,
	ACCOUNT_TYPE      	VARCHAR2(50),
    AVAILABLE_BALANCE	NUMBER(20) 	DEFAULT 0,
	CURRENT_BALANCE		NUMBER(20) 	DEFAULT 0,
	STATUS      		VARCHAR2(50),
	LAST_TXN_NUMBER		VARCHAR2(50),
    CREATED_DATE        TIMESTAMP		NOT NULL,
    UPDATED_DATE        TIMESTAMP,
    CREATED_BY    		VARCHAR2(50) 	NOT NULL,
    UPDATED_BY          VARCHAR2(50)
);
  
ALTER TABLE PARTNER_ACCOUNT ADD CONSTRAINT PARTNER_ACCOUNT_PK PRIMARY KEY(PARTNER_ACCOUNT_ID);
ALTER TABLE PARTNER_ACCOUNT ADD CONSTRAINT PARTNER_ACCOUNT_NUMBER_UNIQUE UNIQUE(ACCOUNT_NUMBER);
ALTER TABLE PARTNER_ACCOUNT ADD FOREIGN KEY(PARTNER_ID) REFERENCES PARTNER(PARTNER_ID);
CREATE SEQUENCE SEQ_PARTNER_ACCOUNT MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;
CREATE SEQUENCE SEQ_PARTNER_ACCOUNT_NUMBER MINVALUE 20000 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 20000 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table PARTNER_ACCOUNT_H
--------------------------------------------------------
CREATE TABLE PARTNER_ACCOUNT_H (
	PARTNER_HISTORY_ID			NUMBER(20) 		NOT NULL,
    PARTNER_ACCOUNT_ID  		NUMBER(20) 		NOT NULL,
    PARTNER_ID    				NUMBER(20),
    ACCOUNT_NUMBER  			NUMBER(15) 	NOT NULL,
	ACCOUNT_TYPE      			VARCHAR2(50),
    AVAILABLE_BALANCE			NUMBER(20),
	CURRENT_BALANCE				NUMBER(20),
	STATUS      				VARCHAR2(50),
    CREATED_DATE        		TIMESTAMP		NOT NULL,
    UPDATED_DATE        		TIMESTAMP,
    CREATED_BY    				VARCHAR2(50) 	NOT NULL,
    UPDATED_BY          		VARCHAR2(50),
	TXN_NUMBER 		    		VARCHAR2(50)
);

ALTER TABLE PARTNER_ACCOUNT_H ADD CONSTRAINT PARTNER_HISTORY_ID_PK PRIMARY KEY(PARTNER_HISTORY_ID);
ALTER TABLE PARTNER_ACCOUNT_H ADD FOREIGN KEY(PARTNER_ACCOUNT_ID) REFERENCES PARTNER_ACCOUNT(PARTNER_ACCOUNT_ID);
CREATE SEQUENCE SEQ_PARTNER_ACCOUNT_H MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table BANK_PARTNER_MAP
--------------------------------------------------------
CREATE TABLE BANK_PARTNER_MAP (
    ID    					NUMBER(20) 		NOT NULL,
    BANK_ID  				NUMBER(20),
    PARTNER_ID 				NUMBER(20)
);
  
ALTER TABLE BANK_PARTNER_MAP ADD CONSTRAINT BANK_PARTNER_MAP_PK PRIMARY KEY(ID);
ALTER TABLE BANK_PARTNER_MAP ADD FOREIGN KEY(BANK_ID) REFERENCES BANK(BANK_ID);
ALTER TABLE BANK_PARTNER_MAP ADD FOREIGN KEY(PARTNER_ID) REFERENCES PARTNER(PARTNER_ID);
CREATE SEQUENCE SEQ_BANK_PARTNER_MAP MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table PARTNER_GROUP
--------------------------------------------------------
CREATE TABLE PARTNER_GROUP (
	ID 						NUMBER(20) 		NOT NULL,
	PROGRAM_MANAGER_ID 		NUMBER(20) 		NOT NULL,
	NAME 					VARCHAR(250) 	NOT NULL,
	DESCRIPTION 			VARCHAR2(255) 	NOT NULL,
	STATUS 					VARCHAR(50) 	NOT NULL,
	REASON 					VARCHAR(500),
	CREATED_DATE 			TIMESTAMP 		NOT NULL,
	UPDATED_DATE 			TIMESTAMP,
	CREATED_BY 				VARCHAR(50) 	NOT NULL,
	UPDATED_BY 				VARCHAR(50)
);

ALTER TABLE PARTNER_GROUP ADD CONSTRAINT PARTNER_GROUP_PK PRIMARY KEY(ID);
ALTER TABLE PARTNER_GROUP ADD FOREIGN KEY(PROGRAM_MANAGER_ID) REFERENCES PROGRAM_MANAGER(ID);
CREATE SEQUENCE SEQ_PARTNER_GROUP MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table PARTNER_GROUP_PARTNER_MAP
--------------------------------------------------------
CREATE TABLE PARTNER_GROUP_PARTNER_MAP (
	ID 						NUMBER(20) NOT NULL,
	PARTNER_GROUP_ID 		NUMBER(20),
	PARTNER_ID 				NUMBER(20) 
);

ALTER TABLE PARTNER_GROUP_PARTNER_MAP ADD CONSTRAINT PARTNER_GROUP_PARTNER_MAP_PK PRIMARY KEY(ID);
ALTER TABLE PARTNER_GROUP_PARTNER_MAP ADD FOREIGN KEY(PARTNER_GROUP_ID) REFERENCES PARTNER_GROUP(ID);
ALTER TABLE PARTNER_GROUP_PARTNER_MAP ADD FOREIGN KEY(PARTNER_ID) REFERENCES PARTNER(PARTNER_ID);
CREATE SEQUENCE SEQ_PARTNER_GROUP_PARTNER_MAP MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table SALESPERSON_PROGRAMMANAGER_MAP
--------------------------------------------------------
CREATE TABLE SALESPERSON_PROGRAMMANAGER_MAP (
	ID 						NUMBER(20) 	NOT NULL,
	PROGRAM_MANAGER_ID 		NUMBER(20),
	SALES_AGENT_ID 			NUMBER(20) 
);

ALTER TABLE SALESPERSON_PROGRAMMANAGER_MAP ADD CONSTRAINT SALESPERs_PM_MAP_PK PRIMARY KEY(ID);
CREATE SEQUENCE SEQ_SALESPERSON_PM_MAP MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table SALES_AGENT
--------------------------------------------------------
CREATE TABLE SALES_AGENT (
	SALES_AGENT_ID 				NUMBER 			NOT NULL,
	SALES_AGENT_NAME 			VARCHAR2(255)   DEFAULT NULL,
	SALES_AGENT_ADDRESS1 		VARCHAR2(50), 
	SALES_AGENT_ADDRESS2 		VARCHAR2(50), 
	SALES_AGENT_COUNTRY 		VARCHAR2(20), 
	SALES_AGENT_STATE 			VARCHAR2(20), 
	SALES_AGENT_CITY 			VARCHAR2(20), 
	SALES_AGENT_ZIPCODE 		VARCHAR2(20),
	SALES_AGENT_PHONENUM 		VARCHAR2(20), 
	SALES_AGENT_PHONEEXT 		VARCHAR2(20), 
	SALES_AGENT_MOBILENUM 		VARCHAR2(20), 
	SALES_AGENT_EMAIL 			VARCHAR2(100), 
	SALES_AGENT_FAX 			VARCHAR2(20), 
	SALES_AGENT_SSN 			VARCHAR2(20), 
	SALES_AGENT_STATUS  		VARCHAR2(20),
	SALES_AGENT_REASON  		VARCHAR2(500),
	CREATED_DATE   				TIMESTAMP	  	NOT NULL,
	UPDATED_DATE  				TIMESTAMP,
	CREATED_BY    				VARCHAR2(50)    NOT NULL,
	UPDATED_BY    				VARCHAR2(50),
	EXTENSION                   VARCHAR2(5)
);

ALTER TABLE SALES_AGENT ADD CONSTRAINT SALES_AGENT_PK PRIMARY KEY(SALES_AGENT_ID);
CREATE SEQUENCE SEQ_SALES_AGENT MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 2 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table SALES_AGENT_BANK_DETAILS
--------------------------------------------------------
CREATE TABLE SALES_AGENT_BANK_DETAILS ( 
	SALES_AGENT_BANK_ID 			NUMBER(20), 
	SALES_AGENT_ID 					NUMBER(20),
	SALES_AGENT_BANKNAME 			VARCHAR2(20), 
	SALES_AGENT_BANKCOUNTRY 		VARCHAR2(20), 
	SALES_AGENT_BANKSTATE 			VARCHAR2(20), 
	SALES_AGENT_BANKCITY 			VARCHAR2(20), 
	SALES_AGENT_BANKROUTINGNUMBER 	VARCHAR2(20),
	SALES_AGENT_BANKACCOUNTNUM 		NUMBER(20), 
	ACCOUNT_TYPE 					VARCHAR2(20)
);

ALTER TABLE SALES_AGENT_BANK_DETAILS ADD CONSTRAINT SALES_AGENT_BANK_ID PRIMARY KEY(SALES_AGENT_BANK_ID);
ALTER TABLE SALES_AGENT_BANK_DETAILS ADD FOREIGN KEY(SALES_AGENT_ID) REFERENCES SALES_AGENT(SALES_AGENT_ID);
CREATE SEQUENCE SEQ_SALES_AGENT_BANK MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 2 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table WHITE_LABEL_CONFIG
--------------------------------------------------------
CREATE TABLE WHITE_LABEL_CONFIG (	
	WHITE_LABEL_CONFIG_ID 		NUMBER(20) 	NOT NULL ENABLE, 
	PARTNER_ID 					NUMBER(20) 	NOT NULL ENABLE, 
	CUSTOMER_THEME_SCHEMA 		VARCHAR2(100), 
	CUSTOM_LOGO 				BLOB, 
	BODY_BG_COLOR 				VARCHAR2(50), 
	HEADER_BG_COLOR 			VARCHAR2(50), 
	HEADER_FONT_COLOR 			VARCHAR2(50), 
	CONTENT_BG_COLOR 			VARCHAR2(50), 
	CONTENT_FONT_COLOR 			VARCHAR2(50), 
	BREAD_CRUMB_BG_COLOR 		VARCHAR2(50), 
	BREAD_CRUMB_FONT_COLOR 		VARCHAR2(50), 
	NAVIGATION_BG_COLOR			VARCHAR2(50), 
	NAVIGATION_ACT_BG_COLOR 	VARCHAR2(50), 
	NAVIGATION_FONT_COLOR 		VARCHAR2(50), 
	CREATED_DATE 				TIMESTAMP(6)	NOT NULL, 
	UPDATED_DATE 				TIMESTAMP(6), 
	CREATED_BY    				VARCHAR2(50) 	NOT NULL,
	UPDATED_BY                  VARCHAR2(50)
);
  
ALTER TABLE WHITE_LABEL_CONFIG ADD CONSTRAINT WHITE_LABEL_CONFIG_PK PRIMARY KEY(WHITE_LABEL_CONFIG_ID);
ALTER TABLE WHITE_LABEL_CONFIG ADD FOREIGN KEY(PARTNER_ID) REFERENCES PARTNER(PARTNER_ID);
CREATE SEQUENCE SEQ_WHITE_LABEL MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;
CREATE SEQUENCE SEQ_CARD MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table ACCOUNT_PROGRAM
--------------------------------------------------------  
CREATE TABLE ACCOUNT_PROGRAM (
    ACCOUNT_PROGRAM_ID            			NUMBER(20)  	NOT NULL,
	ACCOUNT_PROGRAM_NAME          			VARCHAR2(255),
	DESCRIPTION                   			VARCHAR2(255),
	PARTNER_ID                    			NUMBER(20)    	NOT NULL,
	STATUS                        			VARCHAR2(50),
	ACCOUNT_INACTIVE_PERIOD       			NUMBER(20),
	INACTIVITY_PERIOD 						NUMBER(10),
	INACTIVE_PERIOD_DURATION 				VARCHAR2(50),
	CARD_INACTIVITY_PERIOD 					NUMBER(10),
	CARD_INACTIVE_PERIOD_DURATION 			VARCHAR2(50),
	MAINTENANCE_FEE_START_DAYS 				NUMBER(10),
	MAINTENANCE_FREQUENCY_IN_DAYS 			NUMBER(10),
	MAX_BALANCE_LIMIT       	  			NUMBER(20),
	ACCOUNT_CURRENCY						VARCHAR2(255),
	FREE_POS_TRANSACTION       	  			NUMBER(20),
	FREE_ATM_CASH_WITHDRAWAL      			NUMBER(20),
	FREE_BALANCE_INQUIRY       	  			NUMBER(20),
	FREE_LOAD_THROUGH_AGENT		            NUMBER(20),
	FREE_ACCOUNT_TRANSFER       	        NUMBER(20),
	FREE_FUND_TO_BANK       	  	        NUMBER(20),
	FREE_FUND_FROM_BANK       	  	        NUMBER(20),
	REASON 		  				  			VARCHAR2(500),
	CREATED_DATE                  			TIMESTAMP		NOT NULL,
    UPDATED_DATE                  			TIMESTAMP,
    CREATED_BY    				            VARCHAR2(50)   	NOT NULL,
    UPDATED_BY                    			VARCHAR2(50),
    CARD_LOAD_LIMIT                         VARCHAR2(20)
);

ALTER TABLE ACCOUNT_PROGRAM ADD CONSTRAINT ACCOUNT_PROGRAM_PK PRIMARY KEY(ACCOUNT_PROGRAM_ID);
CREATE SEQUENCE SEQ_ACCOUNT_PROGRAM MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;
--------------------------------------------------------
--  DDL for Table ACCOUNT_PROGRAM_LIMITS
--------------------------------------------------------
CREATE TABLE ACCOUNT_PROGRAM_LIMITS (	
	ACCOUNT_PROGRAM_LIMITS_ID  			NUMBER(20)       NOT NULL,
	ACCOUNT_PROGRAM_ID  				NUMBER(20)       NOT NULL,
	TRANSACTION_LIMIT_TYPE				VARCHAR2(255)    NOT NULL,
	PER_TXN_AMOUNT_LIMIT				NUMBER(20),
	DAY_COUNT_LIMIT						NUMBER(20),
	DAY_AMOUNT_LIMIT					NUMBER(20),
	MONTH_COUNT_LIMIT					NUMBER(20),
	MONTH_AMOUNT_LIMIT					NUMBER(20)
);
 
ALTER TABLE ACCOUNT_PROGRAM_LIMITS ADD CONSTRAINT ACCOUNT_PROGRAM_LIMITS_ID_PK PRIMARY KEY(ACCOUNT_PROGRAM_LIMITS_ID);
ALTER TABLE ACCOUNT_PROGRAM_LIMITS ADD FOREIGN KEY(ACCOUNT_PROGRAM_ID) REFERENCES ACCOUNT_PROGRAM(ACCOUNT_PROGRAM_ID);
CREATE SEQUENCE SEQ_ACCOUNT_PROGRAM_LIMITS MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table CARD_PROGRAM
--------------------------------------------------------
CREATE TABLE CARD_PROGRAM (
    CARD_PROGRAM_ID                	NUMBER(20)    NOT NULL,
    CARD_PROGRAM_NAME          		VARCHAR2(255) NOT NULL,
    CARD_PROGRAM_DESCRIPTION       	VARCHAR2(255),
    CARD_TYPE 						VARCHAR2(30),
    BIN                            	NUMBER(20)    NOT NULL,
    BIN_EXT            				VARCHAR2(10),
    PARTNER_ID                  	NUMBER(20),
    BANK_ID 						NUMBER(20),
    ACCOUNT_PROGRAM_ID           	NUMBER(20),
    PHOTO_CARD                     	NUMBER(1),
    PIN_GEN_ALGORITHM              	VARCHAR2(50),
    PIN_VERIFY_ALGORITHM           	VARCHAR2(50),
    PIN_LENGTH                     	NUMBER(20),
    CARD_DESIGN         			VARCHAR2(50),
    SERVICE_CODE 					VARCHAR2(50),
    EMBOSSING_MESSAGE          		VARCHAR2(255),
    MAX_PIN_RETRY_ATTEMPTS         	NUMBER(10),
    CARD_EXPIRY_PERIOD             	NUMBER(10),
    STATUS                         	VARCHAR2(50),
    REASON 		  					VARCHAR2(500),
    CREATED_DATE                   	TIMESTAMP		NOT NULL,
    UPDATED_DATE                   	TIMESTAMP,
    CREATED_BY    				    VARCHAR2(50)   	NOT NULL,
    UPDATED_BY                     	VARCHAR2(50)
);

ALTER TABLE CARD_PROGRAM ADD CONSTRAINT CARD_PROGRAM_PK PRIMARY KEY(CARD_PROGRAM_ID);
ALTER TABLE CARD_PROGRAM ADD FOREIGN KEY(PARTNER_ID)REFERENCES PARTNER(PARTNER_ID);
ALTER TABLE CARD_PROGRAM ADD FOREIGN KEY(ACCOUNT_PROGRAM_ID) REFERENCES ACCOUNT_PROGRAM(ACCOUNT_PROGRAM_ID);
CREATE SEQUENCE SEQ_CARD_PROGRAM MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table CARD_DESIGN
--------------------------------------------------------
CREATE TABLE CARD_DESIGN (
	ID					NUMBER(20) NOT NULL,
	CARD_MANUFACTURER	VARCHAR2(30),
	CARD_TYPE  			VARCHAR2(30),
	CARD_CODE			VARCHAR2(30)
);

ALTER TABLE CARD_DESIGN ADD CONSTRAINT card_design_id_pk PRIMARY KEY(ID);

--------------------------------------------------------
--  DDL for Table FEE_CODE
--------------------------------------------------------
CREATE TABLE FEE_CODE (	
	FEE_CODE 					NUMBER(20), 
	FEE_SHORT_CODE 				VARCHAR2(255), 
	PROC_CODE_TXN_TYPE 			VARCHAR2(10), 
	RESPONSE_CODE 				VARCHAR2(10),
	FEE_DESCRIPTION 			VARCHAR2(255)
);
 
ALTER TABLE FEE_CODE ADD CONSTRAINT FEE_CODE_PK PRIMARY KEY(FEE_CODE);
CREATE SEQUENCE SEQ_FEE_CODE MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table FEE_PROGRAM
--------------------------------------------------------
CREATE TABLE FEE_PROGRAM (	
	FEE_PROGRAM_ID 			    NUMBER(20)    	NOT NULL ENABLE, 
	FEE_PROGRAM_NAME 			VARCHAR2(100), 
	FEE_PROGRAM_DESC 			VARCHAR2(255), 
	ACCOUNT_PROGRAM_ID 			NUMBER(20),
	PARTNER_ID 					NUMBER(20),
	REASON 		  			    VARCHAR2(500),
	CREATED_BY    				VARCHAR2(50)    NOT NULL,
	UPDATED_BY                  VARCHAR2(50),
	CREATED_DATE				TIMESTAMP(6)	NOT NULL, 
	UPDATED_DATE 				TIMESTAMP(6), 
	STATUS 					    VARCHAR2(20)
);
 
ALTER TABLE FEE_PROGRAM ADD CONSTRAINT FEE_PROGRAM_PK PRIMARY KEY(FEE_PROGRAM_ID);
CREATE SEQUENCE SEQ_FEE_PROGRAM MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table FEE_PROGRAM_VALUE
--------------------------------------------------------
CREATE TABLE FEE_PROGRAM_VALUE (	
	FEE_PROGRAM_VALUE_ID 	NUMBER(20) 		NOT NULL ENABLE,
	FEE_CODE 				NUMBER(20) 		NOT NULL ENABLE, 
	FEE_PROGRAM_ID 			NUMBER(20) 		NOT NULL ENABLE, 
	DOM_FEE_TYPE 			VARCHAR2(50), 
	DOM_FIXED_FEE 			NUMBER(20), 
	DOM_MAX_VALUE 			NUMBER(20), 
	DOM_MIN_VALUE 			NUMBER(20), 
	DOM_PERCENTAGE_ONLY 	NUMBER(20), 
	INT_FEE_TYPE 			VARCHAR2(50), 
	INT_FIXED_FEE 			NUMBER(20), 
	INT_MAX_VALUE 			NUMBER(20), 
	INT_MIN_VALUE 			NUMBER(20), 
	INT_PERCENTAGE_ONLY 	NUMBER(20), 
	CREATED_BY    			VARCHAR2(50) 	NOT NULL,
	UPDATED_BY              VARCHAR2(50),
	CREATED_DATE 			TIMESTAMP(6)	NOT NULL, 
	UPDATED_DATE 			TIMESTAMP(6)
);

ALTER TABLE FEE_PROGRAM_VALUE ADD CONSTRAINT FEE_PROGRAM_VALUE_PK PRIMARY KEY(FEE_PROGRAM_VALUE_ID);
ALTER TABLE FEE_PROGRAM_VALUE ADD FOREIGN KEY(FEE_CODE) REFERENCES FEE_CODE(FEE_CODE);
CREATE SEQUENCE SEQ_FEE_PROGRAM_VALUE MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table CUSTOMER_BANK
--------------------------------------------------------
CREATE TABLE CUSTOMER_BANK (
	BANK_ID				NUMBER(20)    NOT NULL,
	BANK_NAME 			VARCHAR2(100),
	ADDRESS 			VARCHAR2(255),
	CITY 				VARCHAR2(100),
	STATE 				VARCHAR2(100),
	COUNTRY 			VARCHAR2(100),
	ZIP 				VARCHAR2(20),
	ACCOUNT_NUMBER 		NUMBER(20),
	ROUTING_NUMBER 		VARCHAR2(20),
	ACCOUNT_TYPE 		VARCHAR2(20),
	NAME_ON_ACCOUNT 	VARCHAR2(100)
);

ALTER TABLE CUSTOMER_BANK ADD CONSTRAINT CUSTOMER_BANK_ID_PK PRIMARY KEY(BANK_ID);
CREATE SEQUENCE SEQ_CUSTOMER_BANK_ID MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

-------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------
CREATE TABLE CUSTOMER (
    CUSTOMER_ID        		NUMBER(20)    NOT NULL,
    PROGRAM_MANAGER_ID		NUMBER(20),
    TITLE 					VARCHAR2(50),
    USERNAME 				VARCHAR2(255),
    FIRST_NAME        		VARCHAR2(100),
    MIDDLE_NAME       		VARCHAR2(50),
    LAST_NAME         		VARCHAR2(100),
    DATE_BIRTH         	 	DATE,
    COMPANY_NAME			VARCHAR2(100),
    EMAIL               	VARCHAR2(255),
    PHONE               	VARCHAR2(20),
    SSN                 	VARCHAR2(50),
    PASSWORD            	VARCHAR2(255),
    COUNTRY_CITIZENSHIP 	VARCHAR2(100),
    COUNTRY_RESIDENCE   	VARCHAR2(100),
    LAST_PASSWORD_CHANGE 	TIMESTAMP(6),
    BANK_ID					NUMBER(20),
    STATUS              	VARCHAR2(50),
    REASON 		  			VARCHAR2(500),
	PASSWORD_HISTORY 		VARCHAR2(500),
	LOGIN_MODE 				NUMBER(10),
	SECURITY_KEY 			VARCHAR2(200),
	SECURITY_QUESTION 		VARCHAR2(100),
	SECURITY_ANSWER 		VARCHAR2(100),
	PASS_RETRY_COUNT 		NUMBER(2),
    CREATED_DATE       		TIMESTAMP		NOT NULL,
    UPDATED_DATE      		TIMESTAMP,
    CREATED_BY    			VARCHAR2(50)   	NOT NULL,
    UPDATED_BY        		VARCHAR2(50),
    EXTENSION               VARCHAR2(5)
);

ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_PK PRIMARY KEY(CUSTOMER_ID);
ALTER TABLE CUSTOMER ADD FOREIGN KEY(BANK_ID) REFERENCES CUSTOMER_BANK(BANK_ID);
CREATE SEQUENCE SEQ_CUSTOMER_ID MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1000 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table CUSTOMER_ADDRESS
--------------------------------------------------------
CREATE TABLE CUSTOMER_ADDRESS (
    ADDRESS_ID 			NUMBER(20)   NOT NULL,
    CUSTOMER_ID 		NUMBER(20), 
    ADDRESS_TYPE		VARCHAR2(50),
    ADDRESS1            VARCHAR2(255),
    ADDRESS2            VARCHAR2(255),
    CITY                VARCHAR2(50),
    STATE               VARCHAR2(50),
    ZIP                 VARCHAR2(20),
    COUNTRY             VARCHAR2(50)
);

ALTER TABLE CUSTOMER_ADDRESS ADD CONSTRAINT CUSTOMER_ADDRESS_PK PRIMARY KEY(ADDRESS_ID);
ALTER TABLE CUSTOMER_ADDRESS ADD FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);
CREATE SEQUENCE SEQ_CUSTOMER_ADDRESS_ID MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1000 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table CUSTOMER_ACCOUNT
--------------------------------------------------------
CREATE TABLE CUSTOMER_ACCOUNT (
	CUSTOMER_ACCOUNT_ID                 	NUMBER(20) 	NOT NULL,
    CUSTOMER_ID             				NUMBER(20),
    PARTNER_ID             					NUMBER(20),
    BANK_ID             					NUMBER(20),
    ACCOUNT_NUMBER             				NUMBER(15) 	NOT NULL,
	ACCOUNT_PROGRAM_ID						NUMBER(20),
	FEE_PROGRAM_ID							NUMBER(20),
	AVAILABLE_BALANCE						NUMBER(20) 	DEFAULT 0,
	CURRENT_BALANCE							NUMBER(20) 	DEFAULT 0,
	ACCOUNT_STATUS       					VARCHAR2(50),
	ACCOUNT_TYPE       						VARCHAR2(20),
	LAST_TRANSACTION_DATE					TIMESTAMP,
	ACCOUNT_INACTIVE_PERIOD					NUMBER(20),
	CARD_INACTIVITY_PERIOD 					NUMBER(10),
	CARD_INACTIVE_PERIOD_DURATION 			VARCHAR2(50),
	MAX_BALANCE_LIMIT						NUMBER(20),
	ACCOUNT_CURRENCY						VARCHAR2(255),		
	AMOUNT_TRANSFER_MODE 					VARCHAR2(20),
	FREE_ATM_CASH_WITHDRAWAL				NUMBER(20),
	FREE_ACCT_TO_ACCT_TRASFER				NUMBER(20),
	FREE_BALANCE_INQUIRY					NUMBER(20),
	FREE_FUND_TRNSFR_FROM_BANK				NUMBER(20),
	FREE_FUND_TRNSFR_TO_BANK				NUMBER(20),
	FREE_LOAD_TXN_THROUGH_AGENT				NUMBER(20),
	FREE_POS_TRANSACTION					NUMBER(20),
	INACTIVITY_PERIOD 						NUMBER(10),
	INACTIVE_PERIOD_DURATION 				VARCHAR2(50),
	REASON									VARCHAR2(500),
	LAST_TXN_NUMBER							VARCHAR2(50),
	NICK_NAME                            	VARCHAR2(100),
	CREATED_DATE               				TIMESTAMP		NOT NULL,
    UPDATED_DATE               				TIMESTAMP,
    CREATED_BY    				            VARCHAR2(50) 	NOT NULL,
    UPDATED_BY                 				VARCHAR2(50),
    CARD_LOAD_LIMIT                         VARCHAR2(20)
);
  
ALTER TABLE CUSTOMER_ACCOUNT ADD CONSTRAINT CUSTOMER_ACCOUNT_PK PRIMARY KEY(CUSTOMER_ACCOUNT_ID);
ALTER TABLE CUSTOMER_ACCOUNT ADD CONSTRAINT CUSTOMER_ACCOUNT_UNIQUE UNIQUE(ACCOUNT_NUMBER);
ALTER TABLE CUSTOMER_ACCOUNT ADD FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);
ALTER TABLE CUSTOMER_ACCOUNT ADD FOREIGN KEY(PARTNER_ID) REFERENCES PARTNER(PARTNER_ID);
ALTER TABLE CUSTOMER_ACCOUNT ADD FOREIGN KEY(BANK_ID) REFERENCES BANK(BANK_ID);
ALTER TABLE CUSTOMER_ACCOUNT ADD FOREIGN KEY(ACCOUNT_PROGRAM_ID) REFERENCES ACCOUNT_PROGRAM(ACCOUNT_PROGRAM_ID);
CREATE SEQUENCE SEQ_CUSTOMER_ACCOUNT MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;
CREATE SEQUENCE SEQ_CUSTOMER_ACCOUNT_NUMBER MINVALUE 70000000000 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 70000000000 NOCACHE NOORDER NOCYCLE;	

--------------------------------------------------------
--  DDL for Table CUSTOMER_ACCOUNT_H
--------------------------------------------------------
CREATE TABLE CUSTOMER_ACCOUNT_H (
	CUSTOMER_HISTORY_ID						NUMBER(20) 	NOT NULL,
	CUSTOMER_ACCOUNT_ID                 	NUMBER(20) 	NOT NULL,
    CUSTOMER_ID             				NUMBER(20) 	NOT NULL,
    ACCOUNT_NUMBER             				NUMBER(15) 	NOT NULL,
	ACCOUNT_PROGRAM_ID						NUMBER(20),
	FEE_PROGRAM_ID							NUMBER(20),
	AVAILABLE_BALANCE						NUMBER(20) 	DEFAULT 0,
	CURRENT_BALANCE							NUMBER(20) 	DEFAULT 0,
	ACCOUNT_STATUS       					VARCHAR2(50),
	ACCOUNT_TYPE       						VARCHAR2(20),
	LAST_TRANSACTION_DATE					TIMESTAMP,
	ACCOUNT_INACTIVE_PERIOD					NUMBER(20),
	MAX_BALANCE_LIMIT						NUMBER(20),
	ACCOUNT_CURRENCY						VARCHAR2(255),					
	FREE_ATM_CASH_WITHDRAWAL				NUMBER(20),
	FREE_ACCT_TO_ACCT_TRASFER				NUMBER(20),
	FREE_BALANCE_INQUIRY					NUMBER(20),
	FREE_FUND_TRNSFR_FROM_BANK				NUMBER(20),
	FREE_FUND_TRNSFR_TO_BANK				NUMBER(20),
	FREE_LOAD_TXN_THROUGH_AGENT				NUMBER(20),
	FREE_POS_TRANSACTION					NUMBER(20),
	REASON									VARCHAR2(500),
	LAST_TXN_NUMBER							VARCHAR2(50),
	CREATED_DATE               				TIMESTAMP		NOT NULL,
    UPDATED_DATE               				TIMESTAMP,
    CREATED_BY    				            VARCHAR2(50) 	NOT NULL,
    UPDATED_BY                 				VARCHAR2(50)
);
  
ALTER TABLE CUSTOMER_ACCOUNT_H ADD CONSTRAINT CUSTOMER_ACCOUNT_H_PK PRIMARY KEY(CUSTOMER_HISTORY_ID);
CREATE SEQUENCE SEQ_CUSTOMER_ACCOUNT_H MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table CUSTOMER_ACCOUNT_LIMITS
--------------------------------------------------------
CREATE TABLE CUSTOMER_ACCOUNT_LIMITS (	
	CUSTOMER_ACCOUNT_LIMITS_ID  		NUMBER(20)    NOT NULL,
	CUSTOMER_ACCOUNT_ID  				NUMBER(20)    NOT NULL,
	TRANSACTION_LIMIT_TYPE				VARCHAR2(255) NOT NULL,
	PER_TXN_AMOUNT_LIMIT				NUMBER(20),
	DAY_COUNT_LIMIT						NUMBER(20),
	DAY_AMOUNT_LIMIT					NUMBER(20),
	MONTH_COUNT_LIMIT					NUMBER(20),
	MONTH_AMOUNT_LIMIT					NUMBER(20)
);
 
ALTER TABLE CUSTOMER_ACCOUNT_LIMITS ADD CONSTRAINT CUSTOMER_ACCOUNT_LIMITS_ID_PK PRIMARY KEY(CUSTOMER_ACCOUNT_LIMITS_ID);
ALTER TABLE CUSTOMER_ACCOUNT_LIMITS ADD FOREIGN KEY(CUSTOMER_ACCOUNT_ID) REFERENCES CUSTOMER_ACCOUNT(CUSTOMER_ACCOUNT_ID);
CREATE SEQUENCE SEQ_CUSTOMER_ACCOUNT_LIMITS MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table AGENT
--------------------------------------------------------
CREATE TABLE AGENT (
	AGENT_ID								NUMBER(20) 		NOT NULL,
	AGENT_NAME								VARCHAR2(100),
	AGENT_TYPE 								VARCHAR2(25),
	AGENT_COMPANY_NAME						VARCHAR2(50),
	PARTNER_ID								NUMBER(20),  
	TIN_SSN									VARCHAR2(15),
	AGENT_ANI								VARCHAR2(50),  
	STATUS									VARCHAR2(15),
	APPROVAL_TYPE							VARCHAR2(30),
	REASON 		  							VARCHAR2(500),
	CREATED_DATE	    					TIMESTAMP  		NOT NULL,
	CREATED_BY    							VARCHAR2(50)   	NOT NULL,
	UPDATED_DATE							TIMESTAMP,
	UPDATED_BY								VARCHAR2(50),
	START_DATE          					TIMESTAMP,
	END_DATE            					TIMESTAMP,
	SALES_AGENT_ID      					NUMBER(20) 		DEFAULT 1 NOT NULL,
	AVERAGE_DAILY_POPULATION 				NUMBER(20),
	AGENT_UID                               VARCHAR2(20) 	UNIQUE,
	UPDATE_CARD_HOLDER_PROFILE 				NUMBER(10),
	RECON_BATCH_FILE_REQUIRED 				NUMBER(10),
	WEEKEND_BATCH_FILE_REQUIRED 			NUMBER(10),
	MODIFY_PIN 								VARCHAR2(20),
	VIEW_NETWORK_TRANSACTION 				VARCHAR2(20),
	VIEW_NONNETWORK_TRANSACTION 			VARCHAR2(20),
	DAILY_LOADREPORT_REQUIRED 				NUMBER(10),
	ACTIVATE_CARD 							VARCHAR2(50)
);

ALTER TABLE AGENT ADD CONSTRAINT agent_pk PRIMARY KEY(AGENT_ID);
ALTER TABLE AGENT ADD FOREIGN KEY(SALES_AGENT_ID) REFERENCES SALES_AGENT(SALES_AGENT_ID);
CREATE SEQUENCE SEQ_AGENT_ID MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 NOCYCLE NOORDER NOCACHE;

--------------------------------------------------------
--  DDL for Table AGENT_ACCOUNT
--------------------------------------------------------
CREATE TABLE AGENT_ACCOUNT (
    AGENT_ACCOUNT_ID    			NUMBER(20)  	NOT NULL,  
    AGENT_ID    					NUMBER(20),
    ACCOUNT_NUMBER  				NUMBER(15) 	NOT NULL,
    ACCOUNT_NAME					VARCHAR2(150),
    AVAILABLE_BALANCE				NUMBER(20) 	DEFAULT 0,
	CURRENT_BALANCE					NUMBER(20) 	DEFAULT 0,
	STATUS      					VARCHAR2(50),
	REASON							VARCHAR2(500),
    CREATED_DATE        			TIMESTAMP		NOT NULL,
    UPDATED_DATE        			TIMESTAMP,
    CREATED_BY    					VARCHAR2(50) 	NOT NULL,
    UPDATED_BY          			VARCHAR2(50),
    AUTO_REPLENISH      			NUMBER(10) 		DEFAULT 0,
    PREFUNDING          			VARCHAR2(20),
    LAST_TXN_NUMBER					VARCHAR2(50),
	UPDATE_CARD_HOLDER_PROFILE 		NUMBER(10),
	RECON_BATCH_FILE_REQUIRED 		NUMBER(10),
	WEEKEND_BATCH_FILE_REQUIRED 	NUMBER(10),
	PIN_AS_LAST_4_DIGITS_OF_SSN 	VARCHAR2(20),
	CURRENCY 						VARCHAR2(10),
	TIMEZONE 						VARCHAR2(30)
);
  
ALTER TABLE AGENT_ACCOUNT ADD CONSTRAINT AGENT_ACCOUNT_PK PRIMARY KEY(AGENT_ACCOUNT_ID);
ALTER TABLE AGENT_ACCOUNT ADD CONSTRAINT AGENT_ACCOUNT_NUMBER_UNIQUE UNIQUE(ACCOUNT_NUMBER);
CREATE SEQUENCE SEQ_AGENT_ACCOUNT MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;
CREATE SEQUENCE SEQ_AGENT_ACCOUNT_NUMBER MINVALUE 1000000000 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1000000000 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table AGENT_ACCOUNT_H
--------------------------------------------------------
CREATE TABLE AGENT_ACCOUNT_H (
	AGENT_HISTORY_ID 				NUMBER(20) 		NOT NULL,
	AGENT_ACCOUNT_ID 				NUMBER(20) 		NOT NULL,
	AGENT_ID 						NUMBER(20),
	ACCOUNT_NUMBER 					NUMBER(15) 		NOT NULL,
	AVAILABLE_BALANCE 				NUMBER(20),
	CURRENT_BALANCE 				NUMBER(20),
	STATUS 							VARCHAR2(50),
	REASON							VARCHAR2(500),
	CREATED_DATE 					TIMESTAMP		NOT NULL,
	UPDATED_DATE 					TIMESTAMP,
	CREATED_BY    				    VARCHAR2(50) 	NOT NULL,
	UPDATED_BY 						VARCHAR2(50),
	AUTO_REPLENISH      			NUMBER(10),
    PREFUNDING          			VARCHAR2(20),
	LAST_TXN_NUMBER				    VARCHAR2(50),
	CURRENCY 						VARCHAR2(10),
	TIMEZONE 						VARCHAR2(30)
);

ALTER TABLE AGENT_ACCOUNT_H ADD CONSTRAINT AGENT_HISTORY_PK PRIMARY KEY(AGENT_HISTORY_ID);
CREATE SEQUENCE SEQ_AGENT_ACCOUNT_H MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table AGENT_BANK_DETAILS
--------------------------------------------------------  
CREATE TABLE AGENT_BANK_DETAILS (
	ID					NUMBER(20) 		NOT NULL,
	AGENT_ID			NUMBER(20) 		NOT NULL,
	AGENT_ACCOUNT_ID 	NUMBER(20),
	BANK_NAME  			VARCHAR2(30) 	NOT NULL,
	ACCOUNT_TYPE 		VARCHAR2(20),
	NAME_ON_ACCOUNT 	VARCHAR2(100),
	ADDRESS1			VARCHAR2(100),
	ADDRESS2			VARCHAR2(100),
	CITY				VARCHAR2(30),
	STATE				VARCHAR2(20),
	COUNTRY				VARCHAR2(20),
	ZIPCODE				VARCHAR2(20),
	ACCOUNT_NUMBER		NUMBER(20) 		NOT NULL,
	ROUTING_NUMBER		VARCHAR2(20) 	NOT NULL
);

ALTER TABLE AGENT_BANK_DETAILS ADD CONSTRAINT agent_bank_detail_pk PRIMARY KEY(ID);
ALTER TABLE AGENT_BANK_DETAILS ADD FOREIGN KEY(AGENT_ID) REFERENCES AGENT(AGENT_ID);
CREATE SEQUENCE SEQ_AGENT_BANK_DETAIL_ID MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 NOCYCLE NOORDER NOCACHE;

--------------------------------------------------------
--  DDL for Table AGENT_CONFIGURATION
--------------------------------------------------------		
CREATE TABLE AGENT_CONFIGURATION (
	ID 								NUMBER(20) NOT NULL,
	AGENT_ID						NUMBER(20) NOT NULL,
	AGENT_ACCOUNT_ID 				NUMBER(20),
	ACCOUNT_THRESHOLD_LIMIT			NUMBER(20),
	HOURLY_LIMIT					NUMBER(20),
	DAILY_LIMIT						NUMBER(20),
	WEEKLY_LIMIT					NUMBER(20),
	MONTHLY_LIMIT					NUMBER(20),
	ISSUE_CARD_FEE_CHARGED_TO		VARCHAR2(15),
	ISSUE_CARD_FEE					NUMBER(15,2),
	CARD_LOAD_FEE_CHARGED_TO 		VARCHAR2(15),
	CARD_LOAD_FEE_CHARGE_TYPE 		VARCHAR2(15),
	CARD_LOAD_FEE_VALUE 			NUMBER(15,2),
	LOAD_CARD_MAX_FEE				NUMBER(15,2)
);

ALTER TABLE AGENT_CONFIGURATION ADD CONSTRAINT agent_config_pk PRIMARY KEY(ID);
ALTER TABLE AGENT_CONFIGURATION ADD FOREIGN KEY(AGENT_ID) REFERENCES AGENT(AGENT_ID);
CREATE SEQUENCE SEQ_AGENT_CONFIGURATION_ID MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 NOCYCLE NOORDER NOCACHE;

--------------------------------------------------------
--  DDL for Table AGENT_ACCOUNT_NUMBER_SERIES
--------------------------------------------------------
CREATE TABLE AGENT_ACCOUNT_NUMBER_SERIES (
	ACCOUNT_NUMBER  	NUMBER(15),
    STATUS 				VARCHAR2(255)
);

--------------------------------------------------------
--  DDL for Table AGENT_ROLE
--------------------------------------------------------
CREATE TABLE AGENT_ROLE	(
	ID 					NUMBER(20),
	AGENT_ID 			NUMBER(20) 		NOT NULL,
	DESCRIPTION 		VARCHAR2(255),
	USER_TYPE 			VARCHAR2(100),
	NAME 				VARCHAR2(100),
	REASON 				VARCHAR2(500),
	STATUS 				VARCHAR2(30),
	CREATED_DATE      	TIMESTAMP      	NOT NULL,
	UPDATED_DATE      	TIMESTAMP,
	CREATED_BY          VARCHAR2(20)    NOT NULL,
	UPDATED_BY        	VARCHAR2(20)   
);

ALTER TABLE AGENT_ROLE ADD CONSTRAINT AGENT_ROLE_PK PRIMARY KEY(ID);
ALTER TABLE AGENT_ROLE ADD FOREIGN KEY(AGENT_ID) REFERENCES AGENT(AGENT_ID);
CREATE SEQUENCE SEQ_AGENT_ROLE MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table AGENT_ROLE_FEATURE_MAP
--------------------------------------------------------
CREATE TABLE AGENT_ROLE_FEATURE_MAP (
	ROLE_FEATURE_MAP_ID 	NUMBER(20),
	AGENT_ROLE_ID 			NUMBER(20) 		NOT NULL,
	FEATURE_ID 				NUMBER(20) 		NOT NULL,
	CREATED_DATE      		TIMESTAMP       NOT NULL,
	UPDATED_DATE      		TIMESTAMP,
	CREATED_BY              VARCHAR2(20)    NOT NULL,
	UPDATED_BY        		VARCHAR2(20)   
);

ALTER TABLE AGENT_ROLE_FEATURE_MAP ADD CONSTRAINT AGENT_ROLE_FMAP_PK PRIMARY KEY(ROLE_FEATURE_MAP_ID);
ALTER TABLE AGENT_ROLE_FEATURE_MAP ADD FOREIGN KEY(AGENT_ROLE_ID) REFERENCES AGENT_ROLE(ID);
CREATE SEQUENCE SEQ_AGENT_ROLE_FEATURE_MAP MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table AGENT_USER
--------------------------------------------------------
CREATE TABLE AGENT_USER (
	AGENT_USER_ID			NUMBER(20)   	NOT NULL,
	AGENT_ID				NUMBER(20)   	NOT NULL,
	ROLE_ID 				NUMBER(20)   	NOT NULL,
	AGENT_USER_LOGIN_NAME	VARCHAR2(30) 	NOT NULL,
	FIRSTNAME 				VARCHAR2(30),
	LASTNAME				VARCHAR2(30),
	EMAIL					VARCHAR2(100),
	CONTACT_NUMBER			VARCHAR2(15),
	USERTYPE				VARCHAR2(30),
	STATUS					VARCHAR2(15),  
	REASON 		  			VARCHAR2(500),
	PREVIOUS_PASSWORDS 		VARCHAR2(500),
	LAST_PASSWORD_CHANGE 	TIMESTAMP(6),
	PASS_RETRY_COUNT 		NUMBER(2),
	SECURITY_KEY			VARCHAR2(255),
	PASSWORD				VARCHAR2(255),
	LOGIN_MODE				NUMBER(10),
	SECURITY_QUESTION		VARCHAR2(255),
	SECURITY_ANSWER			VARCHAR2(255),
	CREATED_DATE	     	TIMESTAMP    	NOT NULL,
	CREATED_BY    			VARCHAR2(50) 	NOT NULL,
	UPDATED_DATE			TIMESTAMP,
	UPDATED_BY              VARCHAR2(50),
	EXTENSION               VARCHAR2(5)
);

ALTER TABLE AGENT_USER ADD CONSTRAINT AGENT_USER_PK PRIMARY KEY(AGENT_USER_ID);
ALTER TABLE AGENT_USER ADD FOREIGN KEY(AGENT_ID) REFERENCES AGENT(AGENT_ID);
CREATE SEQUENCE SEQ_AGENT_USER_ID MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 NOCYCLE NOORDER NOCACHE;

--------------------------------------------------------
--  DDL for Table AGENT_USER_H
--------------------------------------------------------
CREATE TABLE AGENT_USER_H (
	ID  						NUMBER(20)		NOT NULL,
	AGENT_USER_ID         		NUMBER(20)		NOT NULL,
	AGENT_ID              		NUMBER(20)		NOT NULL,
	ROLE_ID               		NUMBER(20)		NOT NULL,
	AGENT_USER_LOGIN_NAME 		VARCHAR2(30)  	NOT NULL,
	FIRSTNAME                   VARCHAR2(30),
	LASTNAME                    VARCHAR2(30),
	EMAIL                       VARCHAR2(100),
	CONTACT_NUMBER              VARCHAR2(15),
	USERTYPE                    VARCHAR2(30),
	STATUS                      VARCHAR2(15),
	REASON                      VARCHAR2(500),
	PREVIOUS_PASSWORDS          VARCHAR2(500),
	LAST_PASSWORD_CHANGE        TIMESTAMP(6),
	PASS_RETRY_COUNT            NUMBER(2),
	SECURITY_KEY                VARCHAR2(255),
	PASSWORD                    VARCHAR2(255),
	LOGIN_MODE                  NUMBER(10),
	SECURITY_QUESTION           VARCHAR2(255),
	SECURITY_ANSWER             VARCHAR2(255),
	CREATED_DATE          		TIMESTAMP(6)	NOT NULL,
	CREATED_BY            		VARCHAR2(50)	NOT NULL,
	UPDATED_DATE                TIMESTAMP(6),
	UPDATED_BY                  VARCHAR2(50),
	EXTENSION                   VARCHAR2(5)
);

ALTER TABLE AGENT_USER_H ADD CONSTRAINT AGENT_USER_H_PK PRIMARY KEY(ID);
ALTER TABLE AGENT_USER_H ADD FOREIGN KEY(AGENT_USER_ID) REFERENCES AGENT_USER(AGENT_USER_ID);
CREATE SEQUENCE SEQ_AGENT_USER_HISTORY MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table CARD_BATCH
--------------------------------------------------------
CREATE TABLE CARD_BATCH (	
	BATCH_ID 				NUMBER(20) 	NOT NULL ENABLE, 
	NO_OF_CARDS 			NUMBER(20) 	NOT NULL ENABLE, 
	BATCH_STATUS 			VARCHAR2(20), 
	AGENT_ID 				NUMBER(20),
	INITIAL_STATUS 			VARCHAR2(20),
	BATCH_TYPE 				VARCHAR2(20),
	CREATED_DATE 			TIMESTAMP(6)	NOT NULL, 
	CREATED_BY    			VARCHAR2(50)	NOT NULL,
	UPDATED_DATE 			TIMESTAMP(6), 
	UPDATED_BY              VARCHAR2(50) 
);
	 
ALTER TABLE CARD_BATCH ADD CONSTRAINT CARD_BATCH_PK PRIMARY KEY(BATCH_ID);	
CREATE SEQUENCE SEQ_CARD_BATCH MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table CARD
--------------------------------------------------------
CREATE TABLE CARD (
    CARD_ID                   		NUMBER(20)    NOT NULL,
    CARD_NUMBER               		VARCHAR2(500) NOT NULL,
    ACCOUNT_ID                		NUMBER(20)    NOT NULL,
    CUSTOMER_ID           	  		NUMBER(20)    NOT NULL,
    CARD_PROGRAM_ID           		NUMBER(20)    NOT NULL,
	ACCOUNT_PROGRAM_ID				NUMBER(20),
    AGENT_ID       			  		NUMBER(20),
    CARD_HOLDER_FIRST_NAME    		VARCHAR2(100),
    CARD_HOLDER_LAST_NAME     		VARCHAR2(100),
    CARD_HOLDER_DATE_OF_BIRTH 		DATE,
    CARD_HOLDER_ADDRESS1      		VARCHAR2(255),
    CARD_HOLDER_ADDRESS2      		VARCHAR2(255),
    CARD_HOLDER_CITY          		VARCHAR2(100),
    CARD_HOLDER_STATE         		VARCHAR2(50),
    CARD_HOLDER_ZIP           		VARCHAR2(20),
    CARD_HOLDER_COUNTRY       		VARCHAR2(50),
    CARD_PERSONALIZE 		  		NUMBER(1),
    CARD_PHOTO 				  		BLOB,
    EXPIRATION_DATE           		DATE,
    PRIMARY_CARD              		NUMBER(1),
    CARD_TYPE                 		VARCHAR2(20),
    CARD_EMBOSSED             		NUMBER(1),
    CARD_BATCH                		NUMBER(20),
    WRONG_PIN_COUNT          		NUMBER(4),
    PIN_OFFSET                		VARCHAR2(20),
    STATUS                    		VARCHAR2(50),
    REASON 		  			  		VARCHAR2(500),
    SERIAL_NUMBER 			  		NUMBER(20),
    CARD_TOKEN 				  		VARCHAR2(500),
    TAV 				      		VARCHAR2(100),
    ITAV 							VARCHAR2(100),
    CARD_LOADED				  		VARCHAR2(10),
    ENABLE_CARD_DOWNLOAD			VARCHAR2(10),
    CARD_LAST_FOUR_DIGITS           VARCHAR2(10), 
    CREATED_DATE              		TIMESTAMP		NOT NULL,
    UPDATED_DATE              		TIMESTAMP,
    ACTIVATION_DATE           		TIMESTAMP,
    CREATED_BY    			  		VARCHAR2(50)   	NOT NULL,
    UPDATED_BY                		VARCHAR2(50),
    CARD_UID                        VARCHAR2(20) 	UNIQUE
);

ALTER TABLE CARD ADD CONSTRAINT CARD_PK PRIMARY KEY(CARD_ID);
ALTER TABLE CARD ADD FOREIGN KEY(ACCOUNT_ID) REFERENCES CUSTOMER_ACCOUNT(CUSTOMER_ACCOUNT_ID);
ALTER TABLE CARD ADD FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);
ALTER TABLE CARD ADD FOREIGN KEY(CARD_PROGRAM_ID) REFERENCES CARD_PROGRAM(CARD_PROGRAM_ID);
ALTER TABLE CARD ADD FOREIGN KEY(AGENT_ID) REFERENCES AGENT(AGENT_ID);

--------------------------------------------------------
--  DDL for Table CARD_H
--------------------------------------------------------
CREATE TABLE CARD_H (
  	CARD_HISTORY_ID				    NUMBER(20)    NOT NULL,
    CARD_ID                   		NUMBER(20)    NOT NULL,
    CARD_NUMBER               		VARCHAR2(500) NOT NULL,
    ACCOUNT_ID                		NUMBER(20)    NOT NULL,
    CUSTOMER_ID           	  		NUMBER(20)    NOT NULL,
    CARD_PROGRAM_ID           		NUMBER(20)    NOT NULL,
    AGENT_ID       			  		NUMBER(20),
    CARD_HOLDER_FIRST_NAME    		VARCHAR2(100),
    CARD_HOLDER_LAST_NAME     		VARCHAR2(100),
    CARD_HOLDER_DATE_OF_BIRTH 		DATE,
    CARD_HOLDER_ADDRESS1      		VARCHAR2(255),
    CARD_HOLDER_ADDRESS2      		VARCHAR2(255),
    CARD_HOLDER_CITY          		VARCHAR2(100),
    CARD_HOLDER_STATE         		VARCHAR2(50),
    CARD_HOLDER_ZIP           		VARCHAR2(20),
    CARD_HOLDER_COUNTRY       		VARCHAR2(50),
    CARD_PERSONALIZE 		  		NUMBER(1),
    CARD_PHOTO 				  		BLOB,
    EXPIRATION_DATE           		DATE,
    PRIMARY_CARD              		NUMBER(1),
    CARD_TYPE                 		VARCHAR2(20),
    CARD_EMBOSSED             		NUMBER(1),
    CARD_BATCH                		NUMBER(20),
    WRONG_PIN_COUNT          		NUMBER(4),
    PIN_OFFSET                		VARCHAR2(20),
    STATUS                    		VARCHAR2(50),
    REASON 		  			  		VARCHAR2(500),
    SERIAL_NUMBER 			  		NUMBER(20),
    CARD_TOKEN 				  		VARCHAR2(500),
    TAV 				      		VARCHAR2(100),
    ITAV 							VARCHAR2(100),
    CARD_LOADED				  		VARCHAR2(10),
    ENABLE_CARD_DOWNLOAD			VARCHAR2(10),
    CARD_LAST_FOUR_DIGITS           VARCHAR2(10), 
    CREATED_DATE              		TIMESTAMP		NOT NULL,
    UPDATED_DATE              		TIMESTAMP,
    ACTIVATION_DATE           		TIMESTAMP,
    CREATED_BY    			  		VARCHAR2(50)   	NOT NULL,
    UPDATED_BY                		VARCHAR2(50)
);
  
ALTER TABLE CARD_H ADD CONSTRAINT CARD_H_PK PRIMARY KEY(CARD_HISTORY_ID);
CREATE SEQUENCE SEQ_CARD_H MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table ADDRESS
--------------------------------------------------------
CREATE TABLE ADDRESS (
	ID						NUMBER(20),
	CUST_AGENT_ID			NUMBER(20),
	TYPE		    		VARCHAR2(10) 	NOT NULL,
	ADDRESS1				VARCHAR2(255),
	ADDRESS2				VARCHAR2(255),
	CITY					VARCHAR2(25),
	STATE					VARCHAR2(25),
	ZIPCODE					VARCHAR2(20),
	COUNTRY					VARCHAR2(15),
	CONTACT_PERSON			VARCHAR2(50),
	CONTACT_PH_NUMBER		VARCHAR2(30),
	CONTACT_MOBILE_NUMBER	VARCHAR2(15),
	CONTACT_PH_EXT 			VARCHAR2(5),
	EMAIL					VARCHAR2(50),
	FAX 					VARCHAR2(50),
	ADDRESS_TYPE            VARCHAR2(50),
	EXTENSION               VARCHAR2(5)
);
	
ALTER TABLE ADDRESS ADD CONSTRAINT address_pk PRIMARY KEY(ID);
--ALTER TABLE ADDRESS ADD CONSTRAINT ADDRESS_CUST_AGENT_ID_TYPE_UQ UNIQUE(CUST_AGENT_ID, TYPE);
CREATE SEQUENCE SEQ_ADDRESS_ID MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 NOCYCLE NOORDER NOCACHE;
	
--------------------------------------------------------
--  DDL for Table ENTITY_TRANSACTION
--------------------------------------------------------
CREATE TABLE ENTITY_TRANSACTION (
	ID					    NUMBER(20)   	NOT NULL,
	TXN_NUMBER 				VARCHAR2(50) 	NOT NULL,
	ACCOUNT_ID  			NUMBER(20)   	NOT NULL, 
	ACCOUNT_TYPE			VARCHAR2(50),
	TXN_TYPE  				VARCHAR2(20),
	TXN_STATUS  			VARCHAR2(50),
	TXN_AMOUNT  			NUMBER(20),
	TXN_CODE  				VARCHAR2(100),
	TXN_DESC 				VARCHAR2(255),
	TXN_REF_NUM  			VARCHAR2(50),
	END_BALANCE 			NUMBER(20),
	TXN_TIME            	TIMESTAMP,
    CREATED_BY    			VARCHAR2(50)  	NOT NULL
);
  
ALTER TABLE ENTITY_TRANSACTION ADD CONSTRAINT ENTITY_TRANSACTION_PK PRIMARY KEY(ID);
ALTER TABLE ENTITY_TRANSACTION ADD CONSTRAINT ENTITY_TXN_NUMBER_UNIQUE UNIQUE(TXN_NUMBER);
CREATE SEQUENCE SEQ_ENTITY_TRANSACTION MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;
CREATE SEQUENCE SEQ_ENTITY_TXN_NUMBER MINVALUE 100000 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 100000 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table AGENT_TRANSACTION
--------------------------------------------------------
CREATE TABLE AGENT_TRANSACTION (
	ID					    NUMBER(20)   NOT NULL,
	TXN_NUMBER 				VARCHAR2(50) NOT NULL,
	ACCOUNT_ID  			NUMBER(20)   NOT NULL, 
	TXN_TYPE  				VARCHAR2(20),
	TXN_STATUS  			VARCHAR2(50),
	TXN_AMOUNT  			NUMBER(20),
	TXN_CODE  				VARCHAR2(50),
	TXN_DESC 				VARCHAR2(255),
	TXN_REF_NUM  			VARCHAR2(50),
	END_BALANCE 			NUMBER(20),
	TXN_TIME            	TIMESTAMP,
    CREATED_BY    			VARCHAR2(50) NOT NULL
);
  
ALTER TABLE AGENT_TRANSACTION ADD CONSTRAINT AGENT_TRANSACTION_PK PRIMARY KEY(ID);
ALTER TABLE AGENT_TRANSACTION ADD CONSTRAINT AGENT_TXN_NUMBER_UNIQUE UNIQUE(TXN_NUMBER);
ALTER TABLE AGENT_TRANSACTION ADD FOREIGN KEY(ACCOUNT_ID) REFERENCES AGENT_ACCOUNT(AGENT_ACCOUNT_ID);
CREATE SEQUENCE SEQ_AGENT_TRANSACTION MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;
CREATE SEQUENCE SEQ_AGENT_TXN_NUMBER MINVALUE 100000 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 100000 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table CUSTOMER_TRANSACTION
--------------------------------------------------------
CREATE TABLE CUSTOMER_TRANSACTION (
	ID    						NUMBER(20)   NOT NULL,
	TXN_NUMBER 					VARCHAR2(50) NOT NULL,
	TXN_REF_NUM  				VARCHAR2(50),
	ACCOUNT_ID  				NUMBER(20)   NOT NULL, 
	CARD_ID						NUMBER(20),
	TXN_TYPE  					VARCHAR2(20),
	TXN_CODE  					VARCHAR2(50),
	TXN_STATUS  				VARCHAR2(50),
	TXN_RISK_STATUS  			VARCHAR2(50),
	TXN_AMOUNT  				NUMBER(20),
	CHARGE_BACK_AMOUNT  		NUMBER(20),
	TXN_DESC 					VARCHAR2(255),
	ISOMESSAGE_ID				NUMBER(20),
	TXN_CLIENT 					VARCHAR2(50),
	PREAUTH_REFID 				NUMBER(20),
	END_BALANCE 				NUMBER(20),
	TXN_TIME            		TIMESTAMP,
	TXN_LOCALE 					VARCHAR2(50),
	TXN_MODE 					VARCHAR2(50)
);
  
ALTER TABLE CUSTOMER_TRANSACTION ADD CONSTRAINT CUSTOMER_TRANSACTION_PK PRIMARY KEY(ID);
ALTER TABLE CUSTOMER_TRANSACTION ADD CONSTRAINT CUSTOMER_TXN_NUMBER_UNIQUE UNIQUE(TXN_NUMBER);
ALTER TABLE CUSTOMER_TRANSACTION ADD FOREIGN KEY(ACCOUNT_ID) REFERENCES CUSTOMER_ACCOUNT(CUSTOMER_ACCOUNT_ID);
ALTER TABLE CUSTOMER_TRANSACTION ADD FOREIGN KEY(CARD_ID) REFERENCES CARD(CARD_ID);
CREATE SEQUENCE SEQ_CUSTOMER_TRANSACTION MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;
CREATE SEQUENCE SEQ_CUSTOMER_TXN_NUMBER MINVALUE 100000 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 100000 NOCACHE NOORDER NOCYCLE;
CREATE SEQUENCE SEQ_TXN_REF_NUMBER MINVALUE 100000 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 100000 NOCACHE NOORDER CYCLE;

--------------------------------------------------------
--  DDL for Table AGENT_TRANSACTION_SUMMARY
--------------------------------------------------------
CREATE TABLE AGENT_TRANSACTION_SUMMARY (
	TRANSACTION_LIMIT_ID    	NUMBER(20) 	NOT NULL,
	ACCOUNT_ID 					NUMBER(20),
	DAY  						VARCHAR2(20),
	DAY_COUNT					NUMBER(20),
	DAY_AMOUNT  				NUMBER(20),
	MONTH  						VARCHAR2(20),
	MONTH_COUNT  				NUMBER(20),
	MONTH_AMOUNT  				NUMBER(20),
	TXN_CODE 					VARCHAR2(50),
	HOUR                        VARCHAR2(20),
	HOUR_COUNT                  NUMBER(20),
	HOUR_AMOUNT                 NUMBER(20),
	WEEK                        VARCHAR2(20),
	WEEK_COUNT                  NUMBER(20),
	WEEK_AMOUNT                 NUMBER(20)
);

ALTER TABLE AGENT_TRANSACTION_SUMMARY ADD CONSTRAINT AGENT_TXN_SUMMARY_PK PRIMARY KEY(TRANSACTION_LIMIT_ID);
ALTER TABLE AGENT_TRANSACTION_SUMMARY ADD FOREIGN KEY(ACCOUNT_ID) REFERENCES AGENT_ACCOUNT(AGENT_ACCOUNT_ID);
CREATE SEQUENCE SEQ_AGENT_TRANSACTION_LIMIT MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table CUSTOMER_TRANSACTION_SUMMARY
--------------------------------------------------------
CREATE TABLE CUSTOMER_TRANSACTION_SUMMARY (
	TRANSACTION_LIMIT_ID    	NUMBER(20) 	NOT NULL,
	ACCOUNT_ID 		            NUMBER(20),
	DAY  						VARCHAR2(20),
	DAY_COUNT					NUMBER(20),
	DAY_AMOUNT  				NUMBER(20),
	MONTH  						VARCHAR2(20),
	MONTH_COUNT  				NUMBER(20),
	MONTH_AMOUNT  				NUMBER(20),
	TXN_CODE 					VARCHAR2(50)
);

ALTER TABLE CUSTOMER_TRANSACTION_SUMMARY ADD CONSTRAINT CUSTOMER_TXN_SUMMARY_PK PRIMARY KEY(TRANSACTION_LIMIT_ID);
ALTER TABLE CUSTOMER_TRANSACTION_SUMMARY ADD FOREIGN KEY(ACCOUNT_ID) REFERENCES CUSTOMER_ACCOUNT(CUSTOMER_ACCOUNT_ID);
CREATE SEQUENCE SEQ_CUSTOMER_TRANSACTION_LIMIT MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table EMBOSSING_FILE_CONFIG
--------------------------------------------------------
CREATE TABLE EMBOSSING_FILE_CONFIG (
	EMBOSSING_FILE_CONFIG_ID		NUMBER(20) 		NOT NULL,
	PARTNER_ID				    NUMBER(20) 		NOT NULL,
	CLIENT_PROGRAM_ID         	VARCHAR2(30),
	ORDER_TYPE                	VARCHAR2(30),
	SHIPMENT_METHOD           	VARCHAR2(30),
	FILE_HEADER_RECORD_MARKER 	VARCHAR2(100), 
	FILE_FORMAT_VERSION       	VARCHAR2(20),
	ORDER_RECORD_MARKER       	VARCHAR2(100), 
	LINE_RECORD_MARKER        	VARCHAR2(100), 
	SIGNATURE_REQUIRED        	VARCHAR2(100), 
	CARD_RECORD_MARKER        	VARCHAR2(100), 
	MESSAGE1                  	VARCHAR2(100), 
	FILE_TRAILER_RECORD_MARKER 	VARCHAR2(100), 
	DEFAULT_FIRST_NAME        	VARCHAR2(100),
	DEFAULT_LAST_NAME         	VARCHAR2(100),
	CREATED_DATE              	TIMESTAMP		NOT NULL,
	UPDATED_DATE              	TIMESTAMP, 
	CREATED_BY    				VARCHAR2(50) 	NOT NULL,
	UPDATED_BY                	VARCHAR2(50)
);

ALTER TABLE EMBOSSING_FILE_CONFIG ADD CONSTRAINT EMBOSSING_FILE_CONFIG_PK PRIMARY KEY(EMBOSSING_FILE_CONFIG_ID);
ALTER TABLE EMBOSSING_FILE_CONFIG ADD FOREIGN KEY(PARTNER_ID) REFERENCES PARTNER(PARTNER_ID);
CREATE SEQUENCE SEQ_EMBOSSING_FILE_CONFIG MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 4 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table EMBOSSING_FILE
--------------------------------------------------------
CREATE TABLE EMBOSSING_FILE (
	EMBOSSING_FILE_ID         NUMBER(20) 		NOT NULL, 
	BATCH_NUMBER				NUMBER(20),
	PARTNER_ID				NUMBER(20),
	AGENT_ID                  NUMBER(20),
	FILE_NAME                 VARCHAR2(200),
	STATUS                    VARCHAR2(100), 
	REASON 					VARCHAR2(500),
	CREATED_DATE              TIMESTAMP		NOT NULL,
	UPDATED_DATE              TIMESTAMP, 
	CREATED_BY    			VARCHAR2(50) 	NOT NULL,
	UPDATED_BY                VARCHAR2(50)
);

ALTER TABLE EMBOSSING_FILE ADD CONSTRAINT EMBOSSING_FILE_PK PRIMARY KEY(EMBOSSING_FILE_ID);
ALTER TABLE EMBOSSING_FILE ADD FOREIGN KEY(PARTNER_ID) REFERENCES PARTNER(PARTNER_ID);
ALTER TABLE EMBOSSING_FILE ADD FOREIGN KEY(AGENT_ID) REFERENCES AGENT(AGENT_ID);
CREATE SEQUENCE SEQ_EMBOSSING_FILE MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table ISOMESSAGES
--------------------------------------------------------
CREATE TABLE ISOMESSAGES (
	MESSAGE_ID                 	NUMBER(20)  		NOT NULL, 
	REQ_ORGINATOR              	VARCHAR2(50) 		NOT NULL,
	REQ_MESSAGE_TYPE           	VARCHAR2(20),
	REQ_MESSAGE                	RAW(2000),
	CARD_SCHEME                	VARCHAR2(50),
	DE02_PAN                   	VARCHAR2(500),
	DE03_PROC_CODE             	VARCHAR2(20),
	REQ_DE04_TXN_AMOUNT        	VARCHAR2(20),
	REQ_DE07_TRANSMISSION_DATE 	VARCHAR2(20),
	DE11_STAN                  	VARCHAR2(100),
	DE12_TXN_TIME              	VARCHAR2(50),
	DE13_TXN_DATE              	VARCHAR2(50),
	DE18_MERCHANT_TYPE         	VARCHAR2(50),
  	DE22_POS_ENTRY             	VARCHAR2(20), 
	DE32_AQUIRER_ID            	VARCHAR2(50),
	DE37_RRN                   	VARCHAR2(50),
	DE43_ACCEPTOR_LOCATION     	VARCHAR2(50),
	DE49_TXN_CURRENCY_CODE     	VARCHAR2(50),
	REQ_DE63_PULSE_DATA       	VARCHAR2(255),
	RES_MESSAGE_TYPE           	VARCHAR2(20),
	RES_MESSAGE                	RAW(2000),
	RES_DE04_TXN_AMOUNT        	VARCHAR2(20),
	RES_DE07_TRANSMISSION_DATE 	VARCHAR2(20),
	DE39_RESPONSE_CODE         	VARCHAR2(10),
	RES_DE63_PULSE_DATA        	VARCHAR2(255),
	REVERSAL_STATUS            	VARCHAR2(20),
	CREATED_DATE               	TIMESTAMP 		DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE ISOMESSAGES ADD CONSTRAINT ISOMESSAGES_PK PRIMARY KEY(MESSAGE_ID);
CREATE SEQUENCE SEQ_ISOMESSAGES MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table RIPD_MERCHANT_DETAILS
--------------------------------------------------------
CREATE TABLE RIPD_MERCHANT_DETAILS (	
	RPID_MERCHANT_ID 			NUMBER(20)   	NOT NULL,
	PAN  						VARCHAR2(500) 	NOT NULL, 
	MCC 						VARCHAR2(50), 
	MERCHANT_NAME 				VARCHAR2(255)  	NOT NULL, 
	MERCHANT_ADDITION_DATA 		VARCHAR2(255), 
	RIPD_REQUIRED 				NUMBER(2)     	DEFAULT 	1,
	CREATED_DATE      			TIMESTAMP     	DEFAULT 	CURRENT_TIMESTAMP,
 	CREATED_BY    				VARCHAR2(50)   	NOT NULL
   );
ALTER TABLE RIPD_MERCHANT_DETAILS ADD CONSTRAINT RIPD_MERCHANT_DETAILS_PK PRIMARY KEY(RPID_MERCHANT_ID);
CREATE SEQUENCE SEQ_RIPD_MERCHANT_DETAILS MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table KEY_EXCHANGE
--------------------------------------------------------
CREATE TABLE KEY_EXCHANGE ( 
 	ID           		NUMBER(5), 
 	SOURCE_KEY    		VARCHAR2(10), 
 	KPV_MFK      		VARCHAR2(300), 
 	KEK_MFK       		VARCHAR2(300), 
 	KPE_MFK         	VARCHAR2(300), 
 	IWK_MFK_PREVIOUS 	VARCHAR2(300), 
 	IWK_MFK          	VARCHAR2(300), 
 	EXCHANGE_DATE       TIMESTAMP
);

ALTER TABLE KEY_EXCHANGE ADD CONSTRAINT KEY_EXCHANGE_PK PRIMARY KEY(ID);

--------------------------------------------------------
--  DDL for Table DECLINED_TRANSACTION
--------------------------------------------------------
CREATE TABLE DECLINED_TRANSACTION (
	ID                    	NUMBER(20) 	NOT NULL,
	PAN                   	VARCHAR2(500) 	NOT NULL,
	MESSAGE_ID            	NUMBER(20) 	NOT NULL,
	TXN_AMOUNT            	NUMBER(20),
	TXN_CODE         	  	VARCHAR2(50),
	DECLINE_REASON        	VARCHAR2(255),
	RESPONSE_CODE_DE39    	VARCHAR2(50),
	RESPONSE_MESSAGE_TYPE 	VARCHAR2(20),
	TRANSACTION_TIME      	TIMESTAMP,
	TXN_LOCALE 				VARCHAR2(50),
	TXN_MODE 				VARCHAR2(50)
);

ALTER TABLE DECLINED_TRANSACTION ADD CONSTRAINT DECLINED_TRANSACTION_PK PRIMARY KEY(ID);
CREATE SEQUENCE SEQ_DECLINED_TRANSACTION MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table PENDING_TRANSFER
--------------------------------------------------------
CREATE TABLE PENDING_TRANSFER (
	ID 					NUMBER(20) 		NOT NULL,
	SRC_ACCOUNT_ID 		NUMBER(20),
	TGT_ACCOUNT_ID 		NUMBER(20),
	SRC_ACCOUNT_TYPE 	VARCHAR2(100),
	TGT_ACCOUNT_TYPE 	VARCHAR2(100),
	PROGRAM_MANAGER_ID 	NUMBER(20),
	PARTNER_ID 			NUMBER(20),
	APPROVER_ID 		NUMBER(20),
	CARD_ID 			NUMBER(20),
	STATUS  			VARCHAR2(20),
	TXN_AMOUNT  		NUMBER(20),
	TXN_CODE    		VARCHAR2(50),
	TXN_REF_NUMBER 		VARCHAR2(10),
	CHANGE_STATUS 		VARCHAR2(50),
	COMMENTS 			VARCHAR2(255),
	CREATED_DATE        TIMESTAMP		NOT NULL,
    UPDATED_DATE        TIMESTAMP,
    CREATED_BY    		VARCHAR2(50) 	NOT NULL,
    UPDATED_BY          VARCHAR2(50)
);

ALTER TABLE PENDING_TRANSFER ADD CONSTRAINT PENDING_TRANSFER_PK PRIMARY KEY(ID);
ALTER TABLE PENDING_TRANSFER ADD FOREIGN KEY(CARD_ID) REFERENCES CARD(CARD_ID);
ALTER TABLE PENDING_TRANSFER ADD FOREIGN KEY(PROGRAM_MANAGER_ID) REFERENCES PROGRAM_MANAGER(ID);
ALTER TABLE PENDING_TRANSFER ADD FOREIGN KEY(PARTNER_ID) REFERENCES PARTNER(PARTNER_ID);
CREATE SEQUENCE SEQ_PENDING_TRANSFER MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table MERCHANT_GRATUITY
--------------------------------------------------------
CREATE TABLE MERCHANT_GRATUITY (
	ID                     NUMBER(20) 		NOT NULL,
	MCC                    NUMBER(20) 		NOT NULL,
	MERCHANT_DESCRIPTION   VARCHAR2(255),
	MERCHANT_CATEGORY      VARCHAR2(100),
	GRATUITY_PERCENTAGE    NUMBER(4,2)
);

ALTER TABLE MERCHANT_GRATUITY ADD CONSTRAINT MERCHANT_GRATUITY_PK PRIMARY KEY(ID);
ALTER TABLE MERCHANT_GRATUITY ADD CONSTRAINT MERCHANT_GRATUITY_UNIQUE UNIQUE(MCC);
CREATE SEQUENCE SEQ_MERCHANT_GRATUITY MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table PREAUTH_TRANSACTION
--------------------------------------------------------
CREATE TABLE PREAUTH_TRANSACTION (
	ID 					         NUMBER(20) 	NOT NULL,
	ACCOUNT_ID  		         NUMBER(20) 	NOT NULL, 
	PAN  				         VARCHAR2(500) NOT NULL, 
	PREAUTH_REF_ID 		         NUMBER(20)  	NOT NULL,
	ORIGINAL_PREAUTH_AMOUNT	     NUMBER(20),
	ONHOLD_PREAUTH_AMOUNT 	     NUMBER(20),
	ACQUIRER_FEE 		         NUMBER(20),
	ISSUER_FEE 			         NUMBER(20),
	GRATUITY_AMOUNT 	         NUMBER(20),
	HOLD_EXPIRATION_DATE 	     DATE,
	ISOMESSAGE_ID 		         NUMBER(20) 	NOT NULL,
	PREAUTH_TXN_TYPE 	         VARCHAR2(50),
	DE11_STAN 			         VARCHAR2(100),
	DE12_TXN_TIME 		         VARCHAR2(50),
	DE13_TXN_DATE 		         VARCHAR2(50),
	DE32_AQUIRER_ID 	         VARCHAR2(50),
	DE37_RRN 			         VARCHAR2(50),
	DE38_AUTH_ID 			     VARCHAR2(10) 	NOT NULL,
	DE48_MERCHANT_NAME 		     VARCHAR2(255),
	DE111_PRIVATEACQ 	         VARCHAR2(255),
	MULTI_SETTLEMENT_AMOUNT      NUMBER(20) 	DEFAULT 0,
	MULTI_SETTLEMENT_COUNT 	     NUMBER(10) 	DEFAULT 0,
	MULTI_SETTLEMENT_SEQUENCE    NUMBER(10) 	DEFAULT 0,
	STATUS 				         VARCHAR2(50),
	TXN_DESC 					 VARCHAR2(255),
	AUTH_RISK_STATUS			 VARCHAR2(50),
	RELEASE_STATUS 		         VARCHAR2(50),
	RELEASE_BY 			         VARCHAR2(20),
	CREATED_DATE      	         TIMESTAMP		NOT NULL,
    UPDATED_DATE       	         TIMESTAMP, 
    CREATED_BY    				 VARCHAR2(50) 	NOT NULL,
    UPDATED_BY        	         VARCHAR2(50)
);

ALTER TABLE PREAUTH_TRANSACTION ADD CONSTRAINT PREAUTH_TRANSACTION_PK PRIMARY KEY(ID);
CREATE SEQUENCE SEQ_PREAUTH_TRANSACTION MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;
CREATE SEQUENCE SEQ_PREAUTH_TXN_REF_NUM MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 300000000 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table PREAUTH_TRANSACTION_H
--------------------------------------------------------
CREATE TABLE PREAUTH_TRANSACTION_H (
	ID					        	NUMBER(20) 		NOT NULL,
	HISTORY_ID 			        	NUMBER(20) 		NOT NULL,
	ACCOUNT_ID  		         	NUMBER(20) 		NOT NULL, 
	PAN  				         	VARCHAR2(500) 	NOT NULL, 
	PREAUTH_REF_ID 		         	NUMBER(20)  	NOT NULL,
	ORIGINAL_PREAUTH_AMOUNT	     	NUMBER(20),
	ONHOLD_PREAUTH_AMOUNT 	     	NUMBER(20),
	ACQUIRER_FEE 		         	NUMBER(20),
	ISSUER_FEE 			         	NUMBER(20),
	GRATUITY_AMOUNT 	         	NUMBER(20),
	HOLD_EXPIRATION_DATE 	     	DATE,
	ISOMESSAGE_ID 		         	NUMBER(20) 		NOT NULL,
	PREAUTH_TXN_TYPE 	        	VARCHAR2(50),
	DE11_STAN 			         	VARCHAR2(100),
	DE12_TXN_TIME 		         	VARCHAR2(50),
	DE13_TXN_DATE 		         	VARCHAR2(50),
	DE32_AQUIRER_ID 	         	VARCHAR2(50),
	DE37_RRN 			         	VARCHAR2(50),
	DE38_AUTH_ID 			     	VARCHAR2(10) 	NOT NULL,
	DE48_MERCHANT_NAME 		     	VARCHAR2(255),
	DE111_PRIVATEACQ 	        	VARCHAR2(255),
	MULTI_SETTLEMENT_AMOUNT      	NUMBER(20) 		DEFAULT 0,
	MULTI_SETTLEMENT_COUNT 	     	NUMBER(10) 		DEFAULT 0,
	MULTI_SETTLEMENT_SEQUENCE    	NUMBER(10) 		DEFAULT 0,
	STATUS 				         	VARCHAR2(50),
	TXN_DESC 					 	VARCHAR2(255),
	AUTH_RISK_STATUS			 	VARCHAR2(50),
	RELEASE_STATUS 		         	VARCHAR2(50),
	RELEASE_BY 			         	VARCHAR2(20),
	CREATED_DATE      	         	TIMESTAMP		NOT NULL,
    UPDATED_DATE       	         	TIMESTAMP, 
    CREATED_BY    				 	VARCHAR2(50) 	NOT NULL,
    UPDATED_BY        	         	VARCHAR2(50)
);

ALTER TABLE PREAUTH_TRANSACTION_H ADD CONSTRAINT PREAUTH_TRANSACTION_H_PK PRIMARY KEY(ID);
CREATE SEQUENCE SEQ_PREAUTH_TRANSACTION_H MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;
CREATE SEQUENCE SEQ_AUTH_ID MINVALUE 100000 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 100000 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table LOGIN_SESSION_DETAILS
--------------------------------------------------------
CREATE TABLE LOGIN_SESSION_DETAILS (
	ID 					NUMBER(20),
	SESSION_ID 			VARCHAR2(255),
	USER_ID 			NUMBER(20) 		NOT NULL,
	USER_NAME 			VARCHAR2(50),
	LOGIN_STATUS 		VARCHAR2(15) 	NOT NULL,
	LOGIN_TIME 			TIMESTAMP,
	LOGOUT_TIME  		TIMESTAMP,
	LAST_ACTIVITY_TIME  TIMESTAMP,
	PORTAL_TYPE 		VARCHAR2(50),
	IP_ADDRESS			VARCHAR2(255),
	BROWSER_TYPE    	VARCHAR2(50) 
);

ALTER TABLE LOGIN_SESSION_DETAILS ADD CONSTRAINT LOGIN_SESSION_DETAILS_PK PRIMARY KEY(ID);
CREATE SEQUENCE SEQ_LOGIN_SESSION_DETAILS MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 3 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table REQUEST_FOR_CARD
--------------------------------------------------------
CREATE TABLE REQUEST_FOR_CARD (
	ID                       		NUMBER(20),
	CUSTOMER_ID                    	NUMBER(20) 		NOT NULL,
	CUSTOMER_ACCOUNT_ID            	NUMBER(20) 		NOT NULL,
	CARD_ID                        	NUMBER(20),
	STATUS                         	VARCHAR2(20),
	REASON                         	VARCHAR2(500),
	CARD_HOLDER_FIRST_NAME     		VARCHAR2(100),
	CARD_HOLDER_LAST_NAME       	VARCHAR2(100),
	CARD_HOLDER_DATE_OF_BIRTH   	DATE,
	CARD_HOLDER_ADDRESS1        	VARCHAR2(255),
	CARD_HOLDER_ADDRESS2        	VARCHAR2(255),
	CARD_HOLDER_CITY            	VARCHAR2(100),
	CARD_HOLDER_STATE           	VARCHAR2(50),
	CARD_HOLDER_ZIP             	VARCHAR2(20),
	CARD_HOLDER_COUNTRY         	VARCHAR2(50),
	CREATED_DATE                	TIMESTAMP 		NOT NULL,
	UPDATED_DATE                	TIMESTAMP,
	CREATED_BY           			VARCHAR2(50)   	NOT NULL,
	UPDATED_BY                  	VARCHAR2(50)
);

ALTER TABLE REQUEST_FOR_CARD ADD CONSTRAINT REQUEST_FOR_CARD_PK PRIMARY KEY(ID);
ALTER TABLE REQUEST_FOR_CARD ADD FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);
ALTER TABLE REQUEST_FOR_CARD ADD FOREIGN KEY(CUSTOMER_ACCOUNT_ID) REFERENCES CUSTOMER_ACCOUNT(CUSTOMER_ACCOUNT_ID);
ALTER TABLE REQUEST_FOR_CARD ADD FOREIGN KEY(CARD_ID) REFERENCES CARD(CARD_ID);
ALTER TABLE REQUEST_FOR_CARD ADD CARD_UPGRADE_TYPE VARCHAR2(50);
CREATE SEQUENCE SEQ_REQUEST_FOR_CARD MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table REPORT_CARD_LOST
--------------------------------------------------------
CREATE TABLE REPORT_CARD_LOST (
	ID               	NUMBER(20) 		NOT NULL,
	CUSTOMER_ID     	NUMBER(20) 		NOT NULL,
	CARD_ID           	NUMBER(20),
	STATUS             	VARCHAR2(20),
	ADDRESS1 			VARCHAR2(250),
	ADDRESS2 			VARCHAR2(250),
	CITY 				VARCHAR2(50),
	STATE 				VARCHAR2(50),
	ZIP 				VARCHAR2(50),
	REASON             	VARCHAR2(500),
	CREATED_DATE    	TIMESTAMP,
	UPDATED_DATE       	TIMESTAMP,
	CREATED_BY      	VARCHAR2(50),
	UPDATED_BY        	VARCHAR2(50)
);

ALTER TABLE REPORT_CARD_LOST ADD CONSTRAINT REPORT_CARD_LOST_PK PRIMARY KEY(ID);
ALTER TABLE REPORT_CARD_LOST ADD FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);
ALTER TABLE REPORT_CARD_LOST ADD FOREIGN KEY(CARD_ID) REFERENCES CARD(CARD_ID);
CREATE SEQUENCE SEQ_REPORT_CARD_LOST MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table APPLICATION_CLIENT
--------------------------------------------------------
CREATE TABLE APPLICATION_CLIENT ( 
	ID  					NUMBER(10) 	NOT NULL ENABLE,
	APP_NAME     			VARCHAR2(100) 	NOT NULL, 
	APP_DESCRIPTION     	VARCHAR2(300) 	NOT NULL, 
	APP_ADMIN_EMAIL     	VARCHAR2(150) 	NOT NULL, 
	APP_CLIENT_NAME     	VARCHAR2(150) 	NOT NULL, 
	APP_CLIENT_EMAIL     	VARCHAR2(150) 	NOT NULL, 
	APP_CLIENT_PHONE     	VARCHAR2(20) 	NOT NULL, 
	APP_CLIENT_ADDRESS     	VARCHAR2(200) 	NOT NULL, 
	APP_CLIENT_CITY     	VARCHAR2(100) 	NOT NULL, 
	APP_CLIENT_COUNTRY     	VARCHAR2(10) 	NOT NULL, 
	APP_CLIENT_ZIP     		VARCHAR2(12) 	NOT NULL,
	APP_CLIENT_ROLE     	VARCHAR2(1000) 	NOT NULL,
	STATUS  				VARCHAR2(50) 	NOT NULL,
	ACTIVE_FROM 			TIMESTAMP  		NOT NULL, 
	ACTIVE_TILL 			TIMESTAMP  		NOT NULL, 
	APP_CLIENT_ID      		VARCHAR2(50) 	NOT NULL,
	APP_CLIENT_ACCESS      	VARCHAR2(100) 	NOT NULL,
	APP_AUTH_USER      		VARCHAR2(50) 	NOT NULL,
	APP_AUTH_PASS      		VARCHAR2(100) 	NOT NULL,
	CREATED_BY       		VARCHAR2(50) 	NOT NULL,
	UPDATED_BY      		VARCHAR2(50),
	CREATED_DATE    		TIMESTAMP  		NOT NULL, 
	UPDATED_DATE    		TIMESTAMP 
);

ALTER TABLE APPLICATION_CLIENT ADD CONSTRAINT APPLICATION_CLIENT_PK PRIMARY KEY(ID);
CREATE SEQUENCE SEQ_APPLICATION_CLIENT MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table UPLOAD_FORM
--------------------------------------------------------  
CREATE TABLE UPLOAD_FORM (
	ID              NUMBER(20) 		NOT NULL ENABLE,
	STATUS          VARCHAR2(20),
	REASON          VARCHAR2(500),
    ENTITY_TYPE     VARCHAR2(20),
	FILE_NAME       VARCHAR2(50),
    FILE_DATA		BLOB,
    CREATED_DATE    TIMESTAMP,
    UPDATED_DATE    TIMESTAMP,
    CREATED_BY    	VARCHAR2(50) 	NOT NULL,
    UPDATED_BY      VARCHAR2(50)
);

ALTER TABLE UPLOAD_FORM ADD CONSTRAINT UPLOAD_FORM_PK PRIMARY KEY(ID);
CREATE SEQUENCE SEQ_UPLOAD_FORM MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table NEWS_FEED
--------------------------------------------------------
CREATE TABLE NEWS_FEED (
	ID 					NUMBER(20) 		NOT NULL,
	ENTITY_TYPE 		VARCHAR(20),
	NEWS_TITLE 			VARCHAR(50),
	NEWS_SUMMARY 		VARCHAR(500),
	STATUS 				VARCHAR(20),
	START_DATE 			TIMESTAMP 		NOT NULL,
	END_DATE 			TIMESTAMP,
	CREATED_DATE 		TIMESTAMP 		NOT NULL,
	UPDATED_DATE 		TIMESTAMP,
	CREATED_BY 			VARCHAR(50) 	NOT NULL,
	UPDATED_BY 			VARCHAR(50)
);

ALTER TABLE NEWS_FEED ADD CONSTRAINT NEWS_FEED_PK PRIMARY KEY(ID);
CREATE SEQUENCE SEQ_NEWS_FEED MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table INTERNAL_MESSAGING_SYSTEM
--------------------------------------------------------
CREATE TABLE INTERNAL_MESSAGING_SYSTEM ( 
	ID 						NUMBER(20)			NOT NULL,
  	TITLE 					VARCHAR2(50) 		NOT NULL,
  	MESSAGE_TYPE 			VARCHAR2(20) 		NOT NULL,
  	SUMMARY 				VARCHAR2(500),
  	STATUS 					VARCHAR2(20),
  	FILE_DATA 				BLOB,
  	EMAIL_ID 				VARCHAR2(255),
  	CREATED_DATE  			TIMESTAMP			NOT NULL,
  	UPDATED_DATE  			TIMESTAMP,
  	CREATED_BY    			VARCHAR2(50)		NOT NULL,
  	UPDATED_BY    			VARCHAR2(50)
);

ALTER TABLE INTERNAL_MESSAGING_SYSTEM ADD CONSTRAINT INTERNAL_MESSAGING_SYSTEM_PK PRIMARY KEY(ID);
CREATE SEQUENCE SEQ_INTERNAL_MESSAGING_SYSTEM MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table FUND_TRANSFER_REQUEST
--------------------------------------------------------
CREATE TABLE FUND_TRANSFER_REQUEST (
    ID    					NUMBER(20)   	NOT NULL,
    ENTITY_TYPE     		VARCHAR2(20) 	NOT NULL,
    SRC_ACCOUNT_ID  		NUMBER(20),
    TGT_ACCOUNT_ID  		NUMBER(20),
    PROGRAM_MANAGER_ID 		NUMBER(20),
	PARTNER_ID 				NUMBER(20),
    APPROVER_ID     		NUMBER(20),
    TXN_AMOUNT      		NUMBER(20),
    TXN_CODE        		VARCHAR2(40),
    TXN_REF_NUMBER  		VARCHAR2(10),
    BANK_NAME       		VARCHAR2(50),
    ROUTING_NUMBER  		VARCHAR2(20),
    ZIP_CODE        		VARCHAR2(20),
    BANK_ACCOUNT_NUMBER 	NUMBER(20),
    BANK_ACCOUNT_NAME   	VARCHAR2(50),
    BANK_ACC_TYPE   		VARCHAR2(50),
    STATUS          		VARCHAR2(50)  	NOT NULL,
    BATCH_ID          		NUMBER(20),
    COMMENTS        		VARCHAR2(100),
    BANK_ADDRESS      		VARCHAR2(250),
    BANK_CITY         		VARCHAR2(100),
    BANK_STATE    			VARCHAR2(100),
    ACCOUNT_CLOSE 			VARCHAR2(50),
    CREATED_DATE    		TIMESTAMP    	NOT NULL,
    UPDATED_DATE    		TIMESTAMP,
    CREATED_BY     			VARCHAR2(50)  	NOT NULL,
    UPDATED_BY      		VARCHAR2(50)
);

ALTER TABLE FUND_TRANSFER_REQUEST ADD CONSTRAINT FUND_TRANSFER_REQUEST_PK PRIMARY KEY(ID);
ALTER TABLE FUND_TRANSFER_REQUEST ADD FOREIGN KEY(PROGRAM_MANAGER_ID) REFERENCES PROGRAM_MANAGER(ID);
ALTER TABLE FUND_TRANSFER_REQUEST ADD FOREIGN KEY(PARTNER_ID) REFERENCES PARTNER(PARTNER_ID);
CREATE SEQUENCE SEQ_FUND_TRANSFER_REQUEST_ID MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;
CREATE SEQUENCE SEQ_FUND_TRAN_REQ_BATCH_ID MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

-------------------------------------------------------
--  DDL for Table SYSTEM_CONFIGURATION
--------------------------------------------------------
CREATE TABLE SYSTEM_INTEGRATION (
    ID 						NUMBER(20)      	NOT NULL,
    PROPERTY_NAME           VARCHAR2(255)   	DEFAULT NULL,
    ENABLE_STATUS           VARCHAR2(20)      	DEFAULT NULL,
    DESCRIPTION      		VARCHAR2(2000)      DEFAULT NULL,
    CREATED_DATE            TIMESTAMP	  		NOT NULL,
    UPDATED_DATE            TIMESTAMP,
    CREATED_BY    			VARCHAR2(20)    	NOT NULL,
    UPDATED_BY              VARCHAR2(20)
);

ALTER TABLE SYSTEM_INTEGRATION ADD CONSTRAINT SYSTEM_INTEGRATION_PK PRIMARY KEY(ID);

--------------------------------------------------------
--  DDL for Table REGIONAL_SETTINGS
--------------------------------------------------------
CREATE TABLE REGIONAL_SETTINGS (
    ID 						NUMBER(20)      	NOT NULL,
    REGIONAL_LANGUAGE       VARCHAR2(255),
    NUMBER_FORMAT         	VARCHAR2(255),
    DATE_FORMAT           	VARCHAR2(255),
    HOUR_FORMAT      		VARCHAR2(255),
    TIME_OFFSET            	VARCHAR2(255),
    USER_SESSION_TIMEOUT    NUMBER(20),
    PAGE_REFRESH_RATE    	NUMBER(20),
    ROW_PER_PAGE            VARCHAR2(255),
	REPORT_END_OFFTIME      VARCHAR2(255),
	CURRENCY              	VARCHAR2(255),
	LOGOUT_TIME_URL         VARCHAR2(255),
	CREATED_DATE            TIMESTAMP	  		NOT NULL,
    UPDATED_DATE            TIMESTAMP,
    CREATED_BY    			VARCHAR2(20)    	NOT NULL,
    UPDATED_BY              VARCHAR2(20)
);

ALTER TABLE REGIONAL_SETTINGS ADD CONSTRAINT REGIONAL_SETTINGS_PK PRIMARY KEY(ID);

--------------------------------------------------------
--  DDL for Table AUDIT_TRAIL
--------------------------------------------------------
CREATE TABLE AUDIT_TRAIL (
    AUDIT_TRAIL_ID 			NUMBER(20)      	NOT NULL,
    MODULE_NAME           	VARCHAR2(255)   	DEFAULT NULL,
    TABLE_NAME            	VARCHAR2(255)   	DEFAULT NULL,
    ACTIVITY_TYPE         	VARCHAR2(255)   	DEFAULT NULL,
    DATA_PK_ID            	NUMBER(20)      	DEFAULT NULL,
    LOGIN_SESSION_ID      	VARCHAR2(255)      	DEFAULT NULL,
    USER_ID 			    VARCHAR2(255)   	DEFAULT NULL,
    AUDIT_DATE            	TIMESTAMP	      	NOT NULL
);

ALTER TABLE AUDIT_TRAIL ADD CONSTRAINT AUDIT_TRAIL_PK PRIMARY KEY(AUDIT_TRAIL_ID);
CREATE SEQUENCE SEQ_AUDIT_TRAIL_ID MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 3 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table AUDIT_TRAIL_DETAILS
--------------------------------------------------------
CREATE TABLE AUDIT_TRAIL_DETAILS (
    AUDIT_TRAIL_DETAILS_ID 	NUMBER(20)      	NOT NULL,
    FIELD_NAME              VARCHAR2(255)   	DEFAULT NULL,
    OLD_VALUE               VARCHAR2(255)   	DEFAULT NULL,
    NEW_VALUE               VARCHAR2(255)   	DEFAULT NULL,
    AUDIT_TRAIL_ID          NUMBER(20)
);

ALTER TABLE AUDIT_TRAIL_DETAILS ADD CONSTRAINT AUDIT_TRAIL_DETAILS_PK PRIMARY KEY(AUDIT_TRAIL_DETAILS_ID);
ALTER TABLE AUDIT_TRAIL_DETAILS ADD FOREIGN KEY(AUDIT_TRAIL_ID) REFERENCES AUDIT_TRAIL(AUDIT_TRAIL_ID);
CREATE SEQUENCE SEQ_AUDIT_TRAIL_DETAILS_ID MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 3 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table USER_ROLE_ENTITY_MAP
--------------------------------------------------------
CREATE TABLE USER_ROLE_ENTITY_MAP (
    ID    					NUMBER(20) 		NOT NULL,
    USER_ROLE_ID  			NUMBER(20),
    BANK_ID 				NUMBER(20),
    PROGRAM_MANAGER_ID 		NUMBER(20),
    SALES_AGENT_ID 			NUMBER(20),
    PARTNER_ID 				NUMBER(20)
);

ALTER TABLE USER_ROLE_ENTITY_MAP ADD CONSTRAINT USER_ROLE_ENTITY_MAP_PK PRIMARY KEY(ID);
ALTER TABLE USER_ROLE_ENTITY_MAP ADD FOREIGN KEY(USER_ROLE_ID) REFERENCES USER_ROLE(USER_ROLE_ID);
ALTER TABLE USER_ROLE_ENTITY_MAP ADD FOREIGN KEY(BANK_ID) REFERENCES BANK(BANK_ID);
ALTER TABLE USER_ROLE_ENTITY_MAP ADD FOREIGN KEY(PROGRAM_MANAGER_ID) REFERENCES PROGRAM_MANAGER(ID);
ALTER TABLE USER_ROLE_ENTITY_MAP ADD FOREIGN KEY(SALES_AGENT_ID) REFERENCES SALES_AGENT(SALES_AGENT_ID);
ALTER TABLE USER_ROLE_ENTITY_MAP ADD FOREIGN KEY(PARTNER_ID) REFERENCES PARTNER(PARTNER_ID);
CREATE SEQUENCE SEQ_USER_ROLE_ENTITY_MAP MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 3 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table ACTIVITY_LOG
--------------------------------------------------------
CREATE TABLE ACTIVITY_LOG (
    ACTIVITY_LOG_ID 			NUMBER(20)      	NOT NULL,
    USER_ID           			VARCHAR2(255)   	DEFAULT NULL,
    LOGIN_SESSION_ID            VARCHAR2(255)   	DEFAULT NULL,
    AUDIT_SECTION         		VARCHAR2(255)   	DEFAULT NULL,
    AUDIT_EVENT            		VARCHAR2(255)   	DEFAULT NULL,
    AUDIT_SERVICE      			VARCHAR2(255)      	DEFAULT NULL,
    REQUEST_DATA 			    VARCHAR2(4000)   	DEFAULT NULL,
    DATA_CHANGE            		VARCHAR2(255)   	DEFAULT NULL,
	STATUS						VARCHAR2(500)      	DEFAULT NULL,
	DESCRIPTION         		VARCHAR2(500)      	DEFAULT NULL,
	ACTIVITY_DATE 				TIMESTAMP      		NOT NULL
);

ALTER TABLE ACTIVITY_LOG ADD CONSTRAINT ACTIVITY_LOG_PK PRIMARY KEY(ACTIVITY_LOG_ID);
CREATE SEQUENCE SEQ_ACTIVITY_LOG_ID MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 3 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table SYSTEM_CONFIGURATION
--------------------------------------------------------
CREATE TABLE SYSTEM_CONFIGURATION (
	ID 					NUMBER(20)    NOT NULL,
	CONFIG_KEY 			VARCHAR2(100) DEFAULT NULL,
	CONFIG_VALUE 		VARCHAR2(255) DEFAULT NULL,
	CONFIG_DESCRIPTION  VARCHAR2(500) DEFAULT NULL
);

ALTER TABLE SYSTEM_CONFIGURATION ADD CONSTRAINT SYSTEM_CONFIGURATION_PK PRIMARY KEY(ID);
CREATE SEQUENCE SEQ_SYSTEM_CONFIGURATION MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;
ALTER TABLE SYSTEM_CONFIGURATION ADD CONSTRAINT system_configuration_unique UNIQUE(CONFIG_KEY);

--------------------------------------------------------
--  DDL for Table ENTITY
--------------------------------------------------------
CREATE TABLE ENTITY (
  	ID            		NUMBER(20)  	NOT NULL,
  	NAME          		VARCHAR2(20)  	NOT NULL,
  	DESCRIPTION 		VARCHAR2(50)
);

ALTER TABLE ENTITY ADD CONSTRAINT ENTITY_PK PRIMARY KEY(ID);

--------------------------------------------------------
--  DDL for Table ENTITY_FEATURE
--------------------------------------------------------
CREATE TABLE ENTITY_FEATURE (
  	ID            		NUMBER(20)       NOT NULL,
  	ENTITY_ID        	NUMBER(20)       NOT NULL,
  	FEATURE_ID 			NUMBER(20)       NOT NULL
);

ALTER TABLE ENTITY_FEATURE ADD CONSTRAINT ENTITY_FEATURE_PK PRIMARY KEY(ID);
ALTER TABLE ENTITY_FEATURE ADD FOREIGN KEY(ENTITY_ID) REFERENCES ENTITY(ID);
CREATE SEQUENCE SEQ_ENTITY_FEATURE MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table MERCHANT_CATEGORY_CODE
--------------------------------------------------------
CREATE TABLE MERCHANT_CATEGORY_CODE (
	MCC_CODE 		VARCHAR2(20) NOT NULL,
	DESCRIPTION 	VARCHAR2(100),
	STATUS 			VARCHAR2(50)
);

ALTER TABLE MERCHANT_CATEGORY_CODE ADD CONSTRAINT MERCHANT_CATEGORY_CODE_PK PRIMARY KEY(MCC_CODE);

--------------------------------------------------------
--  DDL for Table AGENT_MCC_MAP
--------------------------------------------------------
CREATE TABLE AGENT_MCC_MAP (
	ID 			NUMBER(20) NOT NULL,
	AGENT_ID 	NUMBER(20),
	MCC_CODE 	VARCHAR2(20)
);

ALTER TABLE AGENT_MCC_MAP ADD CONSTRAINT AGENT_MCC_MAP_PK PRIMARY KEY(ID);
ALTER TABLE AGENT_MCC_MAP ADD FOREIGN KEY(AGENT_ID) REFERENCES AGENT(AGENT_ID);
ALTER TABLE AGENT_MCC_MAP ADD FOREIGN KEY(MCC_CODE) REFERENCES MERCHANT_CATEGORY_CODE(MCC_CODE);
CREATE SEQUENCE SEQ_AGENT_MCC_MAP MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table SETTLEMENT_REPORT
--------------------------------------------------------
CREATE TABLE SETTLEMENT_REPORT (
	ID 										NUMBER(20) 			NOT NULL,
	PARTNER_ID 								NUMBER(20) 			NOT NULL,
	NETWORK_TRANSACTIONS					NUMBER(20),
	CARD_HOLDER_FEES						NUMBER(20),
	ACQUIRER_FEES							NUMBER(20),
	LOAD_FEE_CHARGED_TO_AGENT				NUMBER(20),
	CARD_ISSUE_FEES_CHARGED_AGENT			NUMBER(20),
	CARD_TRANSFER_TO						NUMBER(20),
	CARD_TRANSFER_FROM						NUMBER(20),
	CARD_LOADS								NUMBER(20),
	CARD_REVERSALS							NUMBER(20),
	EXTERNAL_CARD_LOADS						NUMBER(20),
	EXTERNAL_CARD_REVERSALS					NUMBER(20),
	MANUAL_CUSTOMER_DEBIT					NUMBER(20),
	MANUAL_CUSTOMER_CREDIT					NUMBER(20),
	ACQUIRER_TRANSACTION_REVERSAL			NUMBER(20),
	ACQUIRER_FEE_REVERSAL					NUMBER(20),
	CARD_HOLDER_FEE_REVERSAL				NUMBER(20),
	AGENT_LOAD_FEE_REVERSAL					NUMBER(20),
	REPORT_DATE 							DATE 				NOT NULL,
	CREATED_DATE							TIMESTAMP	  		NOT NULL
);

ALTER TABLE SETTLEMENT_REPORT ADD CONSTRAINT SETTLEMENT_REPORT_PK PRIMARY KEY(ID);
ALTER TABLE SETTLEMENT_REPORT ADD FOREIGN KEY(PARTNER_ID) REFERENCES PARTNER(PARTNER_ID);
CREATE SEQUENCE SEQ_SETTLEMENT_REPORT MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table AGENT_USER_ACCESS_RIGHTS
--------------------------------------------------------
CREATE TABLE AGENT_USER_ACCESS_RIGHTS (
    ID    					NUMBER(20) 		NOT NULL,
	USER_ID    				NUMBER(20) 		NOT NULL,
	FEATURE_ID    			NUMBER(20) 		NOT NULL
);
  
ALTER TABLE AGENT_USER_ACCESS_RIGHTS ADD CONSTRAINT AGENT_USER_ACCESS_RIGHTS PRIMARY KEY(ID);
ALTER TABLE AGENT_USER_ACCESS_RIGHTS ADD FOREIGN KEY(USER_ID) REFERENCES AGENT_USER(AGENT_USER_ID);
CREATE SEQUENCE SEQ_AGENT_USER_ACCESS_RIGHTS MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table PROGRAM_MANAGER_MCC_MAP
--------------------------------------------------------
CREATE TABLE PROGRAM_MANAGER_MCC_MAP (
	ID 						NUMBER(20) 		NOT NULL,
	PROGRAM_MANAGER_ID 		NUMBER(20),
	MCC_CODE 				VARCHAR2(20)
);

ALTER TABLE PROGRAM_MANAGER_MCC_MAP ADD CONSTRAINT PROGRAM_MANAGER_MCC_MAP_PK PRIMARY KEY(ID);
ALTER TABLE PROGRAM_MANAGER_MCC_MAP ADD FOREIGN KEY(PROGRAM_MANAGER_ID) REFERENCES PROGRAM_MANAGER(ID);
ALTER TABLE PROGRAM_MANAGER_MCC_MAP ADD FOREIGN KEY(MCC_CODE) REFERENCES MERCHANT_CATEGORY_CODE(MCC_CODE);
CREATE SEQUENCE SEQ_PROGRAM_MANAGER_MCC_MAP INCREMENT BY 1 MAXVALUE 999999999999 MINVALUE 1 NOCACHE;

--------------------------------------------------------
--  DDL for Table PARTNER_MCC_MAP
--------------------------------------------------------
CREATE TABLE PARTNER_MCC_MAP (
	ID 						NUMBER(20) 		NOT NULL,
	PARTNER_ID 				NUMBER(20),
	MCC_CODE 				VARCHAR2(20)
);

ALTER TABLE PARTNER_MCC_MAP ADD CONSTRAINT PARTNER_MCC_MAP_PK PRIMARY KEY(ID);
ALTER TABLE PARTNER_MCC_MAP ADD FOREIGN KEY(PARTNER_ID) REFERENCES PARTNER(PARTNER_ID);
ALTER TABLE PARTNER_MCC_MAP ADD FOREIGN KEY(MCC_CODE) REFERENCES MERCHANT_CATEGORY_CODE(MCC_CODE);
CREATE SEQUENCE SEQ_PARTNER_MCC_MAP INCREMENT BY 1 MAXVALUE 999999999999 MINVALUE 1 NOCACHE;

--------------------------------------------------------
--  DDL for Table PERSONALIZED_CARD_DETAILS
--------------------------------------------------------
CREATE TABLE PERSONALIZED_CARD_DETAILS (
	 PERSONALIZED_CARD_ID            NUMBER(20)   	NOT NULL,
	 AGENT_ID                        NUMBER(20)   	NOT NULL,
	 CARD_ID                         NUMBER(20),
	 PER_CARD_HOLDER_FIRSTNAME       VARCHAR2(100),
	 PER_CARD_HOLDER_LASTNAME        VARCHAR2(100),
	 PER_CARD_HOLDER_DATE_OF_BIRTH   DATE,
	 CARDHOLDER_SSN                  VARCHAR2(10),
	 CARDHOLDER_DESCRIPTION          VARCHAR2(255),
	 CARDHOLDER_STATUS               VARCHAR2(20),
	 CREATED_DATE                    TIMESTAMP  	NOT NULL,
	 UPDATED_DATE                    TIMESTAMP,
	 CREATED_BY                      VARCHAR2(50) 	NOT NULL,
	 UPDATED_BY                      VARCHAR2(50)
);

ALTER TABLE PERSONALIZED_CARD_DETAILS ADD CONSTRAINT PERSONALIZED_CARD_DETAILS_PK PRIMARY KEY(PERSONALIZED_CARD_ID);
CREATE SEQUENCE SEQ_PERSONALIZED_CARD_DETAILS MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table AID
--------------------------------------------------------
CREATE TABLE AID (
	ID 					NUMBER(20),
	APPLICATION_ID 		VARCHAR2(255) 	NOT NULL,
	APPLICATION_LABEL 	VARCHAR2(255) 	NOT NULL,
	CREATED_DATE 		TIMESTAMP(6) 	NOT NULL,
	UPDATED_DATE 		TIMESTAMP(6),
	CREATED_BY 			VARCHAR2(50) 	NOT NULL,
	UPDATED_BY 			VARCHAR2(50)
);

ALTER TABLE AID ADD CONSTRAINT AID_PK PRIMARY KEY (ID);

--------------------------------------------------------
--  DDL for Table PROFILE_MASTER_DATA
--------------------------------------------------------
CREATE TABLE PROFILE_MASTER_DATA (
	ID 								NUMBER				NOT NULL,
	AIP_DATA                      	VARCHAR2(255),
	APPLICATION_ID                	NUMBER(20),
	APPLICATION_PREFERRED_NAME    	VARCHAR2(255),
	CARD_TRANSACTION_QUALIFIER    	VARCHAR2(255),
	APPLICATION_FILE_LOCATOR      	VARCHAR2(255),
	FORM_FACTOR_VALUE             	VARCHAR2(255),
	PDOL                          	VARCHAR2(255),
	CDOL                          	VARCHAR2(255),
	ISSUER_ACTION_CODE_DEFAULT    	VARCHAR2(255),
	ISSUER_ACTION_CODE_ONLINE     	VARCHAR2(255),
	ISSUER_ACTION_CODE_DECLINE    	VARCHAR2(255),
	CRYPTOGRAM_VERSION_NUMBER     	VARCHAR2(255),
	CREATED_DATE                  	TIMESTAMP			NOT NULL,
	UPDATED_DATE                  	TIMESTAMP,
	CREATED_BY                    	VARCHAR2(50),
	UPDATED_BY                    	VARCHAR2(50)
);

ALTER TABLE PROFILE_MASTER_DATA ADD CONSTRAINT PROFILE_MASTER_DATA_PK PRIMARY KEY (ID);
CREATE SEQUENCE SEQ_PROFILE_MASTER_DATA MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 3 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table CARD_EMV_PARAMETERS
--------------------------------------------------------
CREATE TABLE CARD_EMV_PARAMETERS (
	ID 	           						NUMBER(20)        NOT NULL,
	CARD_PROGRAM_ID                     NUMBER(20)        NOT NULL,
	PROFILE_NAME                   		VARCHAR2(50)      NOT NULL,
	APPLICATION_ID                 		NUMBER(20)		  NOT NULL,
	APPLICATION_PREFERRED_NAME     		VARCHAR2(255),
	AIP_DATA                       		VARCHAR2(1024),
	CUMULATIVE_TRANS_LIMIT              NUMBER(12),
    CUMULATIVE_TRANS_UPPER_LIMIT        NUMBER(12),
    CONSECUTIVE_TRANS_LIMIT             NUMBER(12),
    LOWER_CONSECUTIVE_LIMIT             NUMBER(12),
    UPPER_CONSECUTIVE_LIMIT             NUMBER(12),
    OFFLINE_PIN_TRY_COUNTER             NUMBER(12),
    PAN_SEQUENCE_NUMBER                 NUMBER(12),
	APPLICATION_EFFECTIVE_DATE 			TIMESTAMP(6),
    ISSUER_COUNTRY_CODE 				VARCHAR2(20),
	CRYPTOGRAM_VERSION_NUMBER 			VARCHAR2(50),
    DERIVATION_KEY_INDEX 				VARCHAR2(50),
    CREATED_DATE                   		TIMESTAMP,
    UPDATED_DATE                   		TIMESTAMP,
    CREATED_BY    			       		VARCHAR2(50),
    UPDATED_BY                     		VARCHAR2(50)
);

ALTER TABLE CARD_EMV_PARAMETERS ADD CONSTRAINT CARD_EMV_PARAMETERS_PK PRIMARY KEY (ID);
CREATE SEQUENCE SEQ_CARD_EMV_PARAMETERS MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 3 NOCACHE NOORDER NOCYCLE;	
ALTER TABLE CARD_EMV_PARAMETERS ADD FOREIGN KEY (APPLICATION_ID) REFERENCES AID(ID);
ALTER TABLE CARD_EMV_PARAMETERS ADD FOREIGN KEY (CARD_PROGRAM_ID) REFERENCES CARD_PROGRAM(CARD_PROGRAM_ID);

--------------------------------------------------------
--  DDL for Table CARD_LOAD_FORM_DATA
--------------------------------------------------------
CREATE TABLE CARD_LOAD_FORM_DATA (
	ID 					NUMBER(20)  	NOT NULL,
	ACCOUNT_NUMBER 		NUMBER(15),
	CARD_NUMBER 		VARCHAR2(500),
	TXN_AMOUNT 			NUMBER(20),
	FIRST_NAME 			VARCHAR2(50),
	LAST_NAME 			VARCHAR2(50),
	DATE_OF_BIRTH 		DATE,
	SSN 				VARCHAR2(50),
	ADDRESS 			VARCHAR2(255),
	CITY 				VARCHAR2(50),
	STATE 				VARCHAR2(50),
	ZIP 				VARCHAR2(20),
	PIN 				VARCHAR2(50),
	CREATED_DATE 		TIMESTAMP 		NOT NULL,
	CREATED_BY 			VARCHAR2(50) 	NOT NULL
);

ALTER TABLE CARD_LOAD_FORM_DATA ADD CONSTRAINT CARD_LOAD_FORM_DATA_PK PRIMARY KEY(ID);
CREATE SEQUENCE SEQ_CARD_LOAD_FORM_ID MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table TEMP_PERSONALISE_CARD
--------------------------------------------------------
CREATE TABLE TEMP_PERSONALISE_CARD (
	TEMP_PERSONALISE_CARD_ID		NUMBER(20)      NOT NULL,
    CARD_HOLDER_FIRST_NAME     		VARCHAR2(100),
    CARD_HOLDER_LASTNAME       		VARCHAR2(100),
    DATE_OF_BIRTH              		DATE,
    SSN                        		VARCHAR2(10),
    CREATED_DATE               		TIMESTAMP    	NOT NULL,
    CREATED_BY                 		VARCHAR2(50)    NOT NULL
);

ALTER TABLE TEMP_PERSONALISE_CARD ADD CONSTRAINT TEMP_PERSONALISE_CARD_ID_PK PRIMARY KEY(TEMP_PERSONALISE_CARD_ID);
CREATE SEQUENCE SEQ_TEMP_PERSONALISE_CARD MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

----------------------------------------------------------
-- DDL for Table AGENT_BILLING_INFORMATION
----------------------------------------------------------
CREATE TABLE AGENT_BILLING_INFORMATION (
	ID					NUMBER(20) 		NOT NULL,
	AGENT_ID			NUMBER(20) 		NOT NULL,
	CARD_TYPE 		    VARCHAR2(20),
	CARD_NUMBER        	VARCHAR2(500),
	NAME_ON_CARD 	    VARCHAR2(100),
	EXP_DATE			VARCHAR2(100),
	CVV_CODE			VARCHAR2(100),
	BILLING_ADDRESS		VARCHAR2(255),
	CITY				VARCHAR2(50),
	STATE				VARCHAR2(50),
	ZIPCODE				VARCHAR2(50)
);
ALTER TABLE AGENT_BILLING_INFORMATION ADD CONSTRAINT AGENT_BILLING_INFORMATION_PK PRIMARY KEY(ID);
ALTER TABLE AGENT_BILLING_INFORMATION ADD FOREIGN KEY(AGENT_ID) REFERENCES AGENT(AGENT_ID);
CREATE SEQUENCE SEQ_AGENT_BILLING_INFO_ID MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1000 NOCACHE NOORDER NOCYCLE;


----------------------------------------------------------
-- DDL for Table CUSTOM_CARD_IMAGE
----------------------------------------------------------
CREATE TABLE "CUSTOM_CARD_IMAGE" 
(	"ID" NUMBER(20,0) NOT NULL ENABLE, 
	"CARD_PROGRAM_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"FRONT_IMAGE_PHOTO" BLOB, 
	"BACK_IMAGE_PHOTO" BLOB, 
	 FOREIGN KEY ("CARD_PROGRAM_ID")
	  REFERENCES "CARD_PROGRAM" ("CARD_PROGRAM_ID") ENABLE
);
CREATE SEQUENCE  "SEQ_CUSTOM_CARD_IMAGE_ID"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE ;
