ALTER TABLE bank ADD CONTACT_PERSON_PHONE_TEMP Varchar2(20);

UPDATE bank set CONTACT_PERSON_PHONE_TEMP = CONTACT_PERSON_PHONE;

ALTER TABLE bank DROP COLUMN CONTACT_PERSON_PHONE;

ALTER TABLE bank rename column CONTACT_PERSON_PHONE_TEMP TO CONTACT_PERSON_PHONE;

ALTER TABLE bank ADD CONTACT_PERSON_FAX_TEMP Varchar2(20);

UPDATE bank set CONTACT_PERSON_FAX_TEMP = CONTACT_PERSON_FAX;

ALTER TABLE bank DROP COLUMN CONTACT_PERSON_FAX;

ALTER TABLE bank rename column CONTACT_PERSON_FAX_TEMP TO CONTACT_PERSON_FAX;

ALTER TABLE AGENT_BANK_DETAILS modify ( ACCOUNT_NUMBER NUMBER(20));

ALTER TABLE AGENT_BANK_DETAILS modify ( ROUTING_NUMBER VARCHAR2(20));

CREATE TABLE LOGIN_SESSION_DETAILS(
	ID 				NUMBER(20),
	SESSION_ID 		VARCHAR2(255),
	USER_ID 		NUMBER(20) NOT NULL,
	USER_NAME 		VARCHAR2(50),
	LOGIN_STATUS 	VARCHAR2(15) NOT NULL,
	LOGIN_TIME 		TIMESTAMP,
	LOGOUT_TIME  	TIMESTAMP,
	PORTAL_TYPE 	VARCHAR2(50),
	IP_ADDRESS		VARCHAR2(255)
);

ALTER TABLE LOGIN_SESSION_DETAILS ADD CONSTRAINT LOGIN_SESSION_DETAILS_PK PRIMARY KEY (ID);
CREATE SEQUENCE SEQ_LOGIN_SESSION_DETAILS  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 3 NOCACHE NOORDER NOCYCLE;

CREATE TABLE PENDING_TRANSFER
(
	ID 					NUMBER(10) NOT NULL,
	SRC_ACCOUNT_ID 		NUMBER(10),
	TGT_ACCOUNT_ID 		NUMBER(10),
	APPROVER_ID 		NUMBER(10),
	CARD_ID 			NUMBER(10),
	STATUS  			VARCHAR2(20),
	TXN_AMOUNT  		NUMBER(10),
	TXN_CODE    		VARCHAR2(50),
	TXN_REF_NUMBER 		VARCHAR2(10),
	COMMENTS 			VARCHAR2(255),
	CREATED_DATE        TIMESTAMP	NOT NULL,
    UPDATED_DATE        TIMESTAMP,
    CREATED_BY    		VARCHAR2(20) NOT NULL,
    UPDATED_BY          VARCHAR2(20)
);

ALTER TABLE PENDING_TRANSFER ADD CONSTRAINT PENDING_TRANSFER_PK PRIMARY KEY (ID);

ALTER TABLE PENDING_TRANSFER ADD FOREIGN KEY (CARD_ID) REFERENCES CARD(CARD_ID); 

CREATE SEQUENCE SEQ_PENDING_TRANSFER MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE; 

ALTER TABLE LOGIN_SESSION_DETAILS ADD LAST_ACTIVITY_TIME TIMESTAMP;

ALTER TABLE BIN ADD PAYMENT_SCHEME_NAME varchar2(50) NOT NULL;

ALTER TABLE BIN DROP (PAN_LENGTH,PAYMENT_SCHEME_ID,BIN_TYPE,BIN_CURRENCY);  


ALTER TABLE CARD_PROGRAM ADD (CARD_INACTIVE_PERIOD_DURATION VARCHAR2(50));
ALTER TABLE CARD ADD (CARD_INACTIVITY_PERIOD NUMBER(10,0));
ALTER TABLE CARD ADD (CARD_INACTIVE_PERIOD_DURATION VARCHAR2(50));


ALTER TABLE card ADD CARD_HOLDER_ZIP_TEMP Varchar2(20);

UPDATE card set CARD_HOLDER_ZIP_TEMP = CARD_HOLDER_ZIP;

ALTER TABLE card DROP COLUMN CARD_HOLDER_ZIP;

ALTER TABLE card rename column CARD_HOLDER_ZIP_TEMP TO CARD_HOLDER_ZIP;

ALTER TABLE card DROP COLUMN ONE_DAY_COUNT_CREDIT;
ALTER TABLE card DROP COLUMN ONE_DAY_LIMIT_CREDIT;
ALTER TABLE card DROP COLUMN ONE_DAY_COUNT_DEBIT;
ALTER TABLE card DROP COLUMN ONE_DAY_LIMIT_DEBIT;

ALTER TABLE CUSTOMER_ACCOUNT ADD NICK_NAME VARCHAR2(100);

ALTER TABLE ADDRESS ADD CONTACT_PH_EXT VARCHAR2(5);

CREATE TABLE REQUEST_FOR_CARD(
 ID                              NUMBER(10) PRIMARY KEY,
 CUSTOMER_ID                     NUMBER(20) NOT NULL,
 CUSTOMER_ACCOUNT_ID             NUMBER(20) NOT NULL,
 CARD_ID                         NUMBER(20),
 STATUS                          VARCHAR2(20)  ,
 REASON                          VARCHAR2(255),
 CARD_HOLDER_FIRST_NAME      VARCHAR2 (100),
 CARD_HOLDER_LAST_NAME       VARCHAR2 (100),
 CARD_HOLDER_DATE_OF_BIRTH   DATE,
 CARD_HOLDER_ADDRESS1        VARCHAR2 (255),
 CARD_HOLDER_ADDRESS2        VARCHAR2 (255),
 CARD_HOLDER_CITY            VARCHAR2 (100),
 CARD_HOLDER_STATE           VARCHAR2 (50),
 CARD_HOLDER_ZIP             VARCHAR2 (20),
 CARD_HOLDER_COUNTRY         VARCHAR2 (50),
 CREATED_DATE                TIMESTAMP NOT NULL,
 UPDATED_DATE                TIMESTAMP,
 CREATED_BY           			VARCHAR2(20)   NOT NULL,
 UPDATED_BY                  VARCHAR2(20)
);

ALTER TABLE REQUEST_FOR_CARD ADD CONSTRAINT REQUEST_FOR_CARD_PK PRIMARY KEY (ID);
CREATE SEQUENCE SEQ_REQUEST_FOR_CARD MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;

CREATE TABLE REPORT_CARD_LOST(
 ID               	NUMBER(10) NOT NULL ENABLE,
 CUSTOMER_ID     	NUMBER(20) NOT NULL,
 CARD_ID            NUMBER(20),
 STATUS             VARCHAR2(20),
 REASON             VARCHAR2(255),
 MAILING_ADDRESS    VARCHAR2(255),
 CREATED_DATE    	TIMESTAMP,
 UPDATED_DATE       TIMESTAMP,
 CREATED_BY      	VARCHAR2(20),
 UPDATED_BY        	VARCHAR2(20)
);

ALTER TABLE REPORT_CARD_LOST ADD CONSTRAINT REPORT_CARD_LOST_PK PRIMARY KEY (ID);
CREATE SEQUENCE SEQ_REPORT_CARD_LOST MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;

CREATE TABLE APPLICATION_CLIENT ( 
 ID  					NUMBER(10,0) NOT NULL ENABLE,
 APP_NAME     			VARCHAR2(100) NOT NULL, 
 APP_DESCRIPTION     	VARCHAR2(300) NOT NULL, 
 APP_ADMIN_EMAIL     	VARCHAR2(150) NOT NULL, 
 APP_CLIENT_NAME     	VARCHAR2(150) NOT NULL, 
 APP_CLIENT_EMAIL     	VARCHAR2(150) NOT NULL, 
 APP_CLIENT_PHONE     	VARCHAR2(20) NOT NULL, 
 APP_CLIENT_ADDRESS     VARCHAR2(200) NOT NULL, 
 APP_CLIENT_CITY     	VARCHAR2(100) NOT NULL, 
 APP_CLIENT_COUNTRY     VARCHAR2(10) NOT NULL, 
 APP_CLIENT_ZIP     	VARCHAR2(12) NOT NULL,
 APP_CLIENT_ROLE     	VARCHAR2(1000) NOT NULL,
 STATUS  				VARCHAR2(50) NOT NULL,
 ACTIVE_FROM 			TIMESTAMP  NOT NULL, 
 ACTIVE_TILL 			TIMESTAMP  NOT NULL, 
 APP_CLIENT_ID      	VARCHAR2(50) NOT NULL,
 APP_CLIENT_ACCESS      VARCHAR2(100) NOT NULL,
 APP_AUTH_USER      	VARCHAR2(50) NOT NULL,
 APP_AUTH_PASS      	VARCHAR2(100) NOT NULL,
 CREATED_BY       		VARCHAR2(20) NOT NULL,
 UPDATED_BY      		VARCHAR2(20),
 CREATED_DATE    		TIMESTAMP  NOT NULL, 
 UPDATED_DATE    		TIMESTAMP 
);


CREATE SEQUENCE SEQ_APPLICATION_CLIENT MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
ALTER TABLE APPLICATION_CLIENT ADD CONSTRAINT APPLICATION_CLIENT_PK PRIMARY KEY (ID);

CREATE TABLE SALES_AGENT 
(
  SALES_AGENT_ID NUMBER NOT NULL,
  SALES_AGENT_NAME VARCHAR2(20),
  SALES_AGENT_FIRST_NAME VARCHAR2(20),
  SALES_AGENT_LAST_NAME VARCHAR2(20), 
  SALES_AGENT_ADDRESS1 VARCHAR2(50), 
  SALES_AGENT_ADDRESS2 VARCHAR2(50), 
  SALES_AGENT_COUNTRY VARCHAR2(20), 
  SALES_AGENT_STATE VARCHAR2(20), 
  SALES_AGENT_CITY VARCHAR2(20), 
  SALES_AGENT_ZIPCODE VARCHAR2(20),
  SALES_AGENT_PHONENUM VARCHAR2(20), 
  SALES_AGENT_PHONEEXT VARCHAR2(20), 
  SALES_AGENT_MOBILENUM VARCHAR2(20), 
  SALES_AGENT_EMAIL VARCHAR2(20), 
  SALES_AGENT_FAX VARCHAR2(20), 
  SALES_AGENT_SSN VARCHAR2(20), 
  SALES_AGENT_STATUS  VARCHAR2(20),
  SALES_AGENT_REASON  VARCHAR2(20),
  CREATED_DATE   TIMESTAMP	  NOT NULL,
  UPDATED_DATE  TIMESTAMP,
  CREATED_BY    VARCHAR2(20)    NOT NULL,
  UPDATED_BY    VARCHAR2(20),
  CONSTRAINT SALES_AGENT_PK PRIMARY KEY 
  (
    SALES_AGENT_ID 
  )
  ENABLE 
);

CREATE SEQUENCE  SEQ_SALES_AGENT  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE;

CREATE TABLE SALES_AGENT_BANK_DETAILS
( 
  SALES_AGENT_BANK_ID NUMBER(20,0), 
  SALES_AGENT_ID NUMBER(20,0),
  SALES_AGENT_BANKNAME VARCHAR2(20), 
  SALES_AGENT_BANKCOUNTRY VARCHAR2(20), 
  SALES_AGENT_BANKSTATE VARCHAR2(20), 
  SALES_AGENT_BANKCITY VARCHAR2(20), 
  SALES_AGENT_BANKROUTINGNUMBER VARCHAR2(20),
  SALES_AGENT_BANKACCOUNTNUM NUMBER(20, 0), 
  CONSTRAINT SALES_AGENT_BANK_ID PRIMARY KEY 
  (
    SALES_AGENT_BANK_ID 
  )
  ENABLE 
);

ALTER TABLE SALES_AGENT_BANK_DETAILS  ADD CONSTRAINT sales_agent_id_fk FOREIGN KEY (SALES_AGENT_ID) REFERENCES SALES_AGENT(SALES_AGENT_ID);

CREATE SEQUENCE  SEQ_SALES_AGENT_BANK  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE;

ALTER TABLE AGENT ADD START_DATE TIMESTAMP;
ALTER TABLE AGENT ADD END_DATE TIMESTAMP;
ALTER TABLE AGENT ADD SALES_AGENT_ID NUMBER(20) DEFAULT 1 NOT NULL
ALTER TABLE AGENT  ADD CONSTRAINT sales_agent_fk FOREIGN KEY (SALES_AGENT_ID) REFERENCES SALES_AGENT(SALES_AGENT_ID);

ALTER TABLE AGENT_ACCOUNT ADD AUTO_REPLENISH NUMBER(10);
ALTER TABLE AGENT_ACCOUNT ADD PREFUNDING VARCHAR2(20);

ALTER TABLE AGENT_USER modify ( USERTYPE VARCHAR2(30));

ALTER TABLE SALES_AGENT modify ( SALES_AGENT_EMAIL VARCHAR2(100));

CREATE TABLE UPLOAD_FORM (
	ID              NUMBER(10) NOT NULL ENABLE,
	STATUS          VARCHAR2(20),
	REASON          VARCHAR2(250),
    ENTITY_TYPE     VARCHAR2(20),
	FILE_NAME       VARCHAR2(50),
    FILE_DATA		BLOB,
    CREATED_DATE    TIMESTAMP,
    UPDATED_DATE    TIMESTAMP,
    CREATED_BY    	VARCHAR2(20) NOT NULL,
    UPDATED_BY      VARCHAR2(20)
);

ALTER TABLE UPLOAD_FORM ADD CONSTRAINT UPLOAD_FORM_PK PRIMARY KEY (ID);

CREATE SEQUENCE SEQ_UPLOAD_FORM MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER  NOCYCLE ;

--  DDL for Table INTERNAL_MESSAGING_SYSTEM
--------------------------------------------------------
CREATE TABLE INTERNAL_MESSAGING_SYSTEM ( 
	ID 						NUMBER(20)			NOT NULL,
  	TITLE 					VARCHAR2(50) 		NOT NULL,
  	MESSAGE_TYPE 			VARCHAR2(20) 		NOT NULL,
  	PRIORITY  				VARCHAR2(20) 		NOT NULL,
  	SUMMARY 				VARCHAR2(500),
  	STATUS 					VARCHAR2(20),
  	FILE_DATA 				BLOB,
  	EMAIL_ID 				VARCHAR2(255),
  	CREATED_DATE  			TIMESTAMP			NOT NULL,
  	UPDATED_DATE  			TIMESTAMP,
  	CREATED_BY    			VARCHAR2(20)		NOT NULL,
  	UPDATED_BY    			VARCHAR2(20)
);

ALTER TABLE INTERNAL_MESSAGING_SYSTEM ADD CONSTRAINT INTERNAL_MESSAGING_SYSTEM_PK PRIMARY KEY (ID);
CREATE SEQUENCE SEQ_INTERNAL_MESSAGING_SYSTEM MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;


ALTER TABLE CARD ADD CARD_LAST_FOUR_DIGITS Varchar2(10);

ALTER TABLE CUSTOMER_ACCOUNT ADD AMOUNT_TRANSFER_MODE VARCHAR2(20);

ALTER TABLE AGENT ADD APPROVAL_TYPE VARCHAR2(30);

ALTER TABLE AGENT_BANK_DETAILS ADD AGENT_ACCOUNT_ID NUMBER(20);

ALTER TABLE AGENT_CONFIGURATION ADD AGENT_ACCOUNT_ID NUMBER(20);

ALTER TABLE EMBOSSING_FILE ADD REASON VARCHAR2(250);

ALTER TABLE AGENT_ACCOUNT ADD REASON VARCHAR2(250);

ALTER TABLE PREAUTH_TRANSACTION ADD TXN_DESC VARCHAR2(250);
ALTER TABLE PREAUTH_TRANSACTION_H ADD TXN_DESC VARCHAR2(250);

CREATE TABLE PROGRAM_MANAGER (
    ID    					NUMBER(20) 		NOT NULL,
    COMPANY_NAME  			VARCHAR2(100),
    BUSINESS_NAME 			VARCHAR2(100),
    PROGRAM_MANAGER_NAME  	VARCHAR2(255),
    CONTACT_NAME  			VARCHAR2(50),
    CONTACT_PHONE 			VARCHAR2(20),
    CONTACT_EMAIL 			VARCHAR2(100),
    STATUS        			VARCHAR2(50),
    REASON 		  			VARCHAR2(255),
    CREATED_DATE  			TIMESTAMP 		NOT NULL,
    UPDATED_DATE  			TIMESTAMP,
    CREATED_BY    			VARCHAR2(20) 	NOT NULL,
    UPDATED_BY    			VARCHAR2(20)
);
  
ALTER TABLE PROGRAM_MANAGER ADD CONSTRAINT PROGRAM_MANAGER_PK PRIMARY KEY (ID);
CREATE SEQUENCE SEQ_PROGRAM_MANAGER MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table PARTNER
--------------------------------------------------------
CREATE TABLE BANK_PROGRAM_MANAGER_MAP (
    ID    					NUMBER(20) 		NOT NULL,
    BANK_ID  				NUMBER(20)		NOT NULL,
    PROGRAM_MANAGER_ID 		NUMBER(20)		NOT NULL
);
  
ALTER TABLE BANK_PROGRAM_MANAGER_MAP ADD CONSTRAINT BANK_PROGRAM_MANAGER_MAP_PK PRIMARY KEY (ID);
ALTER TABLE BANK_PROGRAM_MANAGER_MAP ADD FOREIGN KEY (BANK_ID) REFERENCES BANK(BANK_ID);
ALTER TABLE BANK_PROGRAM_MANAGER_MAP ADD FOREIGN KEY (PROGRAM_MANAGER_ID) REFERENCES PROGRAM_MANAGER(ID);
CREATE SEQUENCE SEQ_BANK_PROGRAM_MANAGER_MAP MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

ALTER TABLE PARTNER ADD PROGRAM_MANAGER_ID NUMBER(20);
ALTER TABLE PARTNER DROP COLUMN BANK_ID;

ALTER TABLE PARTNER ADD FOREIGN KEY (PROGRAM_MANAGER_ID) REFERENCES PROGRAM_MANAGER(ID);

--------------------------------------------------------
--  DDL for Table BANK_PARTNER_MAP
--------------------------------------------------------
CREATE TABLE BANK_PARTNER_MAP (
    ID    					NUMBER(20) 		NOT NULL,
    BANK_ID  				NUMBER(20),
    PARTNER_ID 				NUMBER(20)
);
  
ALTER TABLE BANK_PARTNER_MAP ADD CONSTRAINT BANK_PARTNER_MAP_PK PRIMARY KEY (ID);
ALTER TABLE BANK_PARTNER_MAP ADD FOREIGN KEY (BANK_ID) REFERENCES BANK(BANK_ID);
ALTER TABLE BANK_PARTNER_MAP ADD FOREIGN KEY (PARTNER_ID) REFERENCES PARTNER(PARTNER_ID);
CREATE SEQUENCE SEQ_BANK_PARTNER_MAP MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

ALTER TABLE PORTAL_ROLE_FEATURE_MAP ADD USER_TYPE VARCHAR2(250) not null;


--------------------------------------------------------
--  DDL for Table PARTNER_GROUP
--------------------------------------------------------

CREATE TABLE PARTNER_GROUP(
	ID 						NUMBER(20) NOT NULL,
	PROGRAM_MANAGER_ID 		NUMBER(20) NOT NULL,
	NAME 					VARCHAR(250) NOT NULL,
	DESCRIPTION 			VARCHAR2(250) NOT NULL,
	STATUS 					VARCHAR(50) NOT NULL,
	REASON 					VARCHAR(250),
	CREATED_DATE 			TIMESTAMP NOT NULL,
	UPDATED_DATE 			TIMESTAMP,
	CREATED_BY 				VARCHAR(20) NOT NULL,
	UPDATED_BY 				VARCHAR(20)
);

ALTER TABLE PARTNER_GROUP ADD CONSTRAINT PARTNER_GROUP_PK PRIMARY KEY (ID);  
ALTER TABLE PARTNER_GROUP ADD FOREIGN KEY (PROGRAM_MANAGER_ID) REFERENCES PROGRAM_MANAGER(ID);

CREATE SEQUENCE SEQ_PARTNER_GROUP MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--------------------------------------------------------
--  DDL for Table PARTNER_GROUP_PARTNER_MAP
--------------------------------------------------------

CREATE TABLE PARTNER_GROUP_PARTNER_MAP(
	ID 						NUMBER(20) NOT NULL,
	PARTNER_GROUP_ID 		NUMBER(20) NOT NULL,
	PARTNER_ID 				NUMBER(20) NOT NULL
);

ALTER TABLE PARTNER_GROUP_PARTNER_MAP ADD CONSTRAINT PARTNER_GROUP_PARTNER_MAP_PK PRIMARY KEY (ID);  
ALTER TABLE PARTNER_GROUP_PARTNER_MAP ADD FOREIGN KEY (PARTNER_GROUP_ID) REFERENCES PARTNER_GROUP(ID);
ALTER TABLE PARTNER_GROUP_PARTNER_MAP ADD FOREIGN KEY (PARTNER_ID) REFERENCES PARTNER(PARTNER_ID);

CREATE SEQUENCE SEQ_PARTNER_GROUP_PARTNER_MAP MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;


ALTER TABLE CUSTOMER ADD PROGRAM_MANAGER_ID NUMBER(20);
ALTER TABLE CUSTOMER_ACCOUNT ADD PARTNER_ID NUMBER(20);
ALTER TABLE CUSTOMER_ACCOUNT ADD BANK_ID NUMBER(20);
ALTER TABLE CUSTOMER_ACCOUNT ADD FOREIGN KEY (PARTNER_ID) REFERENCES PARTNER(PARTNER_ID);
ALTER TABLE CUSTOMER_ACCOUNT ADD FOREIGN KEY (BANK_ID) REFERENCES BANK(BANK_ID);


ALTER TABLE REPORT_CARD_LOST ADD ADDRESS1 VARCHAR2 (255);
ALTER TABLE REPORT_CARD_LOST ADD ADDRESS2 VARCHAR2 (255);
ALTER TABLE REPORT_CARD_LOST ADD CITY VARCHAR2 (50); 
ALTER TABLE REPORT_CARD_LOST ADD STATE VARCHAR2 (50);
ALTER TABLE REPORT_CARD_LOST ADD ZIP VARCHAR2 (20);
ALTER TABLE REPORT_CARD_LOST DROP COLUMN MAILING_ADDRESS;

ALTER TABLE CARD_PROGRAM ADD BANK_ID NUMBER (20);

ALTER TABLE CUSTOMER_TRANSACTION ADD TXN_SUSPECTED VARCHAR2(50);

CREATE TABLE NEWS_FEED (
	ID 					NUMBER(20) 		NOT NULL,
	ENTITY_TYPE 		VARCHAR(20),
	NEWS_TITLE 			VARCHAR(50),
	NEWS_SUMMARY 		VARCHAR(500),
	STATUS 				VARCHAR(20),
	START_DATE 			TIMESTAMP 		NOT NULL,
	END_DATE 			TIMESTAMP,
	CREATED_DATE 		TIMESTAMP 		NOT NULL,
	UPDATED_DATE 		TIMESTAMP,
	CREATED_BY 			VARCHAR(20) 	NOT NULL,
	UPDATED_BY 			VARCHAR(20)
);

ALTER TABLE NEWS_FEED ADD CONSTRAINT NEWS_FEED_PK PRIMARY KEY (ID);
CREATE SEQUENCE SEQ_NEWS_FEED MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

CREATE TABLE FUND_TRANSFER_REQUEST 
(
    ID    NUMBER(20)     NOT NULL,
    ENTITY_TYPE     VARCHAR2(20) NOT NULL,
    SRC_ACCOUNT_ID  NUMBER(10),
    TGT_ACCOUNT_ID  NUMBER(10),
    APPROVER_ID     NUMBER(10),
    TXN_AMOUNT      NUMBER(10),
    TXN_CODE        VARCHAR2(40),
    TXN_REF_NUMBER  VARCHAR2(10),
    BANK_NAME       VARCHAR2(50),
    ROUTING_NUMBER  VARCHAR2(20),
    ZIP_CODE        VARCHAR2(20),
    BANK_ACCOUNT_NUMBER  NUMBER(20),
    BANK_ACCOUNT_NAME    VARCHAR2(50),
    BANK_ACCOUNT_TYPE   VARCHAR2(50),
    STATUS          VARCHAR2(50)    NOT NULL,
    BATCH_ID          	NUMBER(20),
    COMMENTS        VARCHAR2(100),
    CREATED_DATE    TIMESTAMP   NOT NULL,
    UPDATED_DATE    TIMESTAMP,
    CREATED_BY     VARCHAR2(20)    NOT NULL,
    UPDATED_BY      VARCHAR2(20)
);

ALTER TABLE FUND_TRANSFER_REQUEST ADD CONSTRAINT FUND_TRANSFER_REQUEST_PK PRIMARY KEY (ID);

CREATE SEQUENCE SEQ_FUND_TRANSFER_REQUEST_ID MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;
CREATE SEQUENCE SEQ_FUND_TRAN_REQ_BATCH_ID MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

ALTER TABLE USER_ROLE ADD ENTITY_ID NUMBER(20);
ALTER TABLE AGENT_USER ADD ROLE_ID NUMBER(20);

ALTER TABLE INTERNAL_MESSAGING_SYSTEM DROP COLUMN PRIORITY;

CREATE TABLE SYSTEM_INTEGRATION 
(
    ID 						NUMBER(20)      	NOT NULL,
    PROPERTY_NAME           VARCHAR2(255)   	DEFAULT NULL,
    ENABLE_STATUS           VARCHAR2(20)      	DEFAULT NULL,
    DESCRIPTION      		VARCHAR2(2000)      DEFAULT NULL,
    CREATED_DATE            TIMESTAMP	  		NOT NULL,
    UPDATED_DATE            TIMESTAMP,
    CREATED_BY    			VARCHAR2(20)    	NOT NULL,
    UPDATED_BY              VARCHAR2(20)
);

ALTER TABLE SYSTEM_INTEGRATION ADD CONSTRAINT SYSTEM_INTEGRATION_PK PRIMARY KEY (ID);

CREATE TABLE REGIONAL_SETTINGS 
(
    ID 						NUMBER(20)      	NOT NULL,
    REGIONAL_LANGUAGE       VARCHAR2(255),
    NUMBER_FORMAT         	VARCHAR2(255),
    DATE_FORMAT           	VARCHAR2(255),
    HOUR_FORMAT      		VARCHAR2(255),
    TIME_OFFSET            	VARCHAR2(255),
    USER_SESSION_TIMEOUT    NUMBER(20),
    PAGE_REFRESH_RATE    	NUMBER(20),
    ROW_PER_PAGE            VARCHAR2(255),
	REPORT_END_OFFTIME      VARCHAR2(255),
	CURRENCY              	VARCHAR2(255),
	LOGOUT_TIME_URL         VARCHAR2(255),
	CREATED_DATE            TIMESTAMP	  		NOT NULL,
    UPDATED_DATE            TIMESTAMP,
    CREATED_BY    			VARCHAR2(20)    	NOT NULL,
    UPDATED_BY              VARCHAR2(20)
);

ALTER TABLE REGIONAL_SETTINGS ADD CONSTRAINT REGIONAL_SETTINGS_PK PRIMARY KEY (ID);

CREATE TABLE AUDIT_TRAIL 
(
    AUDIT_TRAIL_ID 			NUMBER(20)      	NOT NULL,
    MODULE_NAME           	VARCHAR2(255)   	DEFAULT NULL,
    TABLE_NAME            	VARCHAR2(255)   	DEFAULT NULL,
    ACTIVITY_TYPE         	VARCHAR2(255)   	DEFAULT NULL,
    DATA_PK_ID            	NUMBER(20)      	DEFAULT NULL,
    LOGIN_SESSION_ID      	VARCHAR2(255)      	DEFAULT NULL,
    USER_ID 			    VARCHAR2(255)   	DEFAULT NULL,
    AUDIT_DATE            	TIMESTAMP	      	NOT NULL
);

ALTER TABLE AUDIT_TRAIL ADD CONSTRAINT AUDIT_TRAIL_PK PRIMARY KEY (AUDIT_TRAIL_ID);
CREATE SEQUENCE SEQ_AUDIT_TRAIL_ID  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE;

CREATE TABLE AUDIT_TRAIL_DETAILS 
(
    AUDIT_TRAIL_DETAILS_ID 	NUMBER(20)      	NOT NULL,
    FIELD_NAME              VARCHAR2(255)   	DEFAULT NULL,
    OLD_VALUE               VARCHAR2(255)   	DEFAULT NULL,
    NEW_VALUE               VARCHAR2(255)   	DEFAULT NULL,
    AUDIT_TRAIL_ID          NUMBER(20)
);

ALTER TABLE AUDIT_TRAIL_DETAILS ADD CONSTRAINT AUDIT_TRAIL_DETAILS_PK PRIMARY KEY (AUDIT_TRAIL_DETAILS_ID);
ALTER TABLE AUDIT_TRAIL_DETAILS ADD CONSTRAINT AUDIT_TRAIL_DETAILS_ID_FK FOREIGN KEY (AUDIT_TRAIL_ID) REFERENCES AUDIT_TRAIL(AUDIT_TRAIL_ID);
CREATE SEQUENCE SEQ_AUDIT_TRAIL_DETAILS_ID  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE;

ALTER TABLE admin_user ADD entity_id NUMBER(20);

UPDATE admin_user set entity_id = partner_id;

ALTER TABLE admin_user DROP COLUMN admin_user;

ALTER TABLE USER_ROLE modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE USER_ROLE modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE ADMIN_USER modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE ADMIN_USER modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE BANK modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE BANK modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE PROGRAM_MANAGER modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE PROGRAM_MANAGER modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE PROGRAM_MANAGER_ACCOUNT modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE PROGRAM_MANAGER_ACCOUNT modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE PARTNER modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE PARTNER modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE PARTNER_GROUP modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE PARTNER_GROUP modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE PORTAL_ROLE_FEATURE_MAP modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE PORTAL_ROLE_FEATURE_MAP modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE ACCOUNT_PROGRAM modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE ACCOUNT_PROGRAM modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE SALES_AGENT modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE SALES_AGENT modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE AGENT modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE AGENT modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE BIN modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE BIN modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE CARD modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE CARD modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE CARD_PROGRAM modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE CARD_PROGRAM modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE CUSTOMER modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE CUSTOMER modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE FEE_PROGRAM modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE FEE_PROGRAM modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE FEE_PROGRAM_VALUE modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE FEE_PROGRAM_VALUE modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE SECURITY_QUESTIONS modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE SECURITY_QUESTIONS modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE AGENT_USER modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE AGENT_USER modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE CARD_BATCH modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE CARD_BATCH modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE CUSTOMER_ACCOUNT_PROFILE modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE CUSTOMER_ACCOUNT_PROFILE modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE CUSTOMER_ACCOUNT modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE CUSTOMER_ACCOUNT modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE CUSTOMER_ACCOUNT_H modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE CUSTOMER_ACCOUNT_H modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE AGENT_ACCOUNT modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE AGENT_ACCOUNT modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE AGENT_ACCOUNT_H modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE AGENT_ACCOUNT_H modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE PARTNER_ACCOUNT modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE PARTNER_ACCOUNT modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE PARTNER_ACCOUNT_H modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE PARTNER_ACCOUNT_H modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE ENTITY_TRANSACTION modify ( CREATED_BY VARCHAR2(50));

ALTER TABLE AGENT_TRANSACTION modify ( CREATED_BY VARCHAR2(50));

ALTER TABLE EMBOSSING_FILE_CONFIG modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE EMBOSSING_FILE_CONFIG modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE EMBOSSING_FILE modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE EMBOSSING_FILE modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE PENDING_TRANSFER modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE PENDING_TRANSFER modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE PREAUTH_TRANSACTION modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE PREAUTH_TRANSACTION modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE REQUEST_FOR_CARD modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE REQUEST_FOR_CARD modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE REPORT_CARD_LOST modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE REPORT_CARD_LOST modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE APPLICATION_CLIENT modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE APPLICATION_CLIENT modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE UPLOAD_FORM modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE UPLOAD_FORM modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE NEWS_FEED modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE NEWS_FEED modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE INTERNAL_MESSAGING_SYSTEM modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE INTERNAL_MESSAGING_SYSTEM modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE FUND_TRANSFER_REQUEST modify ( CREATED_BY VARCHAR2(50));
ALTER TABLE FUND_TRANSFER_REQUEST modify ( UPDATED_BY VARCHAR2(50));

ALTER TABLE AGENT_ROLE ADD USER_TYPE VARCHAR2(100);
ALTER TABLE AGENT_ROLE DROP COLUMN ROLE_TYPE;

ALTER TABLE PROGRAM_MANAGER ADD PROGRAMLOGO BLOB;

CREATE TABLE USER_ROLE_ENTITY_MAP (
    ID    					NUMBER(20) 		NOT NULL,
    USER_ROLE_ID  			NUMBER(20),
    BANK_ID 				NUMBER(20),
    PROGRAM_MANAGER_ID 		NUMBER(20),
    SALES_AGENT_ID 			NUMBER(20),
    PARTNER_ID 				NUMBER(20)
);
ALTER TABLE USER_ROLE_ENTITY_MAP ADD CONSTRAINT USER_ROLE_ENTITY_MAP_PK PRIMARY KEY (ID);
CREATE SEQUENCE SEQ_USER_ROLE_ENTITY_MAP  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE;	
 

ALTER TABLE ENTITY_TRANSACTION modify ( TXN_CODE VARCHAR2(100));

ALTER TABLE PENDING_TRANSFER ADD SRC_ACCOUNT_TYPE VARCHAR2(100);
ALTER TABLE PENDING_TRANSFER ADD TGT_ACCOUNT_TYPE VARCHAR2(100);

ALTER TABLE AGENT_BANK_DETAILS ADD ACCOUNT_TYPE VARCHAR2(20);
ALTER TABLE AGENT_BANK_DETAILS drop column NAME_ON_ACCCOUNT;
ALTER TABLE AGENT_BANK_DETAILS ADD NAME_ON_ACCOUNT VARCHAR2(100);
ALTER TABLE AGENT_ROLE modify ( USER_TYPE VARCHAR2(100));

CREATE TABLE ACTIVITY_LOG 
(
    ACTIVITY_LOG_ID 			NUMBER(20)      	NOT NULL,
    USER_ID           			VARCHAR2(255)   	DEFAULT NULL,
    LOGIN_SESSION_ID            VARCHAR2(255)   	DEFAULT NULL,
    AUDIT_SECTION         		VARCHAR2(255)   	DEFAULT NULL,
    AUDIT_EVENT            		VARCHAR2(255)   	DEFAULT NULL,
    AUDIT_SERVICE      			VARCHAR2(255)      	DEFAULT NULL,
    REQUEST_DATA 			    VARCHAR2(4000)   	DEFAULT NULL,
    DATA_CHANGE            		VARCHAR2(255)   	DEFAULT NULL,
	STATUS						VARCHAR2(500)      	DEFAULT NULL,
	DESCRIPTION         		VARCHAR2(500)      	DEFAULT NULL,
	ACTIVITY_DATE 				TIMESTAMP      		NOT NULL
);

ALTER TABLE ACTIVITY_LOG ADD CONSTRAINT ACTIVITY_LOG_PK PRIMARY KEY (ACTIVITY_LOG_ID);
CREATE SEQUENCE SEQ_ACTIVITY_LOG_ID  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE;

drop sequence SEQ_CARD_BATCH;
CREATE SEQUENCE SEQ_CARD_BATCH MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

ALTER TABLE CARD ADD ENABLE_CARD_DOWNLOAD VARCHAR2(10);


ALTER TABLE AGENT ADD AGENT_CLIENT_ID_TEMP VARCHAR2(10);
UPDATE AGENT SET AGENT_CLIENT_ID_TEMP = AGENT_CLIENT_ID;
ALTER TABLE AGENT DROP COLUMN AGENT_CLIENT_ID;
ALTER TABLE AGENT RENAME column AGENT_CLIENT_ID_TEMP TO AGENT_CLIENT_ID;

ALTER TABLE USER_ROLE modify (REASON VARCHAR2(500));
ALTER TABLE ADMIN_USER modify (REASON VARCHAR2(500));
ALTER TABLE BANK modify (REASON VARCHAR2(500));
ALTER TABLE PROGRAM_MANAGER modify (REASON VARCHAR2(500));
ALTER TABLE PARTNER modify (REASON VARCHAR2(500));
ALTER TABLE PARTNER_GROUP modify ( DESCRIPTION VARCHAR2(255));
ALTER TABLE PARTNER_GROUP modify (REASON VARCHAR2(500));
ALTER TABLE ADMIN_USER_H modify (REASON VARCHAR2(500));
ALTER TABLE ACCOUNT_PROGRAM modify (REASON VARCHAR2(500));
ALTER TABLE SALES_AGENT modify ( SALES_AGENT_REASON VARCHAR2(500));
ALTER TABLE AGENT modify (REASON VARCHAR2(500));
ALTER TABLE BIN modify (REASON VARCHAR2(500));
ALTER TABLE CARD modify (REASON VARCHAR2(500));
ALTER TABLE CARD_PROGRAM modify (REASON VARCHAR2(500));
ALTER TABLE CUSTOMER modify (REASON VARCHAR2(500));
ALTER TABLE FEE_PROGRAM modify (REASON VARCHAR2(500));
ALTER TABLE AGENT_USER modify (REASON VARCHAR2(500));
ALTER TABLE CUSTOMER_ACCOUNT_PROFILE modify (REASON VARCHAR2(500));
ALTER TABLE CUSTOMER_ACCOUNT modify (REASON VARCHAR2(500));
ALTER TABLE CUSTOMER_ACCOUNT_H modify (REASON VARCHAR2(500));
ALTER TABLE AGENT_ACCOUNT modify (REASON VARCHAR2(500));
ALTER TABLE EMBOSSING_FILE modify (REASON VARCHAR2(500));
ALTER TABLE REQUEST_FOR_CARD modify (REASON VARCHAR2(500));
ALTER TABLE REPORT_CARD_LOST modify (REASON VARCHAR2(500));
ALTER TABLE UPLOAD_FORM modify (REASON VARCHAR2(500));
ALTER TABLE AGENT_ROLE modify ( DESCRIPTION VARCHAR2(255));
ALTER TABLE AGENT_ROLE modify (REASON VARCHAR2(500));

ALTER TABLE LOGIN_SESSION_DETAILS ADD BROWSER_TYPE VARCHAR2(50);

ALTER TABLE AGENT_ACCOUNT ADD LAST_TXN_NUMBER VARCHAR2(50);
ALTER TABLE AGENT_ACCOUNT_H ADD REASON VARCHAR2(500);
ALTER TABLE AGENT_ACCOUNT_H ADD AUTO_REPLENISH NUMBER(10);
ALTER TABLE AGENT_ACCOUNT_H ADD PREFUNDING VARCHAR2(20);
ALTER TABLE AGENT_ACCOUNT_H ADD LAST_TXN_NUMBER VARCHAR2(20);

ALTER TABLE PARTNER_ACCOUNT ADD LAST_TXN_NUMBER VARCHAR2(20);
ALTER TABLE PROGRAM_MANAGER_ACCOUNT ADD LAST_TXN_NUMBER VARCHAR2(20);

ALTER TABLE AGENT_ACCOUNT modify (AUTO_REPLENISH NUMBER(10) DEFAULT 0);
ALTER TABLE SALES_AGENT DROP COLUMN SALES_AGENT_FIRST_NAME;
ALTER TABLE SALES_AGENT DROP COLUMN SALES_AGENT_LAST_NAME;

ALTER TABLE PENDING_TRANSFER ADD PROGRAM_MANAGER_ID NUMBER(20);
ALTER TABLE PENDING_TRANSFER ADD PARTNER_ID NUMBER(20);

ALTER TABLE FUND_TRANSFER_REQUEST ADD PROGRAM_MANAGER_ID NUMBER(20);
ALTER TABLE FUND_TRANSFER_REQUEST ADD PARTNER_ID NUMBER(20);

CREATE TABLE SYSTEM_CONFIGURATION
(
	ID 					NUMBER(20)    NOT NULL,
	CONFIG_KEY 			VARCHAR2(100) DEFAULT NULL,
	CONFIG_VALUE 		VARCHAR2(255) DEFAULT NULL,
	CONFIG_DESCRIPTION  VARCHAR2(500) DEFAULT NULL
);
ALTER TABLE SYSTEM_CONFIGURATION ADD CONSTRAINT SYSTEM_CONFIGURATION_PK PRIMARY KEY (ID);
CREATE SEQUENCE SEQ_SYSTEM_CONFIGURATION  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE;
ALTER TABLE SYSTEM_CONFIGURATION ADD CONSTRAINT system_configuration_unique UNIQUE (CONFIG_KEY);

ALTER TABLE FUND_TRANSFER_REQUEST ADD ACCOUNT_CLOSE VARCHAR2(50);

ALTER TABLE AGENT  ADD RODEO_COMMITTEE VARCHAR2(20);
ALTER TABLE AGENT  ADD TAX_IDENTIFICATION_NUMBER VARCHAR2(20);
ALTER TABLE AGENT  ADD TAX_YEAR NUMBER(20);
