version: '3'
services:
  web:
    image: nginx
    ports:
    - "9098:80"
    depends_on:
        - db
  db:
    image: mysql
    ports:
    - "3308:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin
    - MYSQL_DATABASE=demodb
  app:
      image: myapp
      ports:
      - "9012:9012"